<?php
$DAIAplus = $this->DAIAplus();

$hideLink = $DAIAplus->hideAvailabilityInfo($this->driver, true);
$hideDaia = $DAIAplus->hideAvailabilityInfo($this->driver);
?>
<? if (!$hideDaia): ?>
<div class="availabilityItem" data-id="<?=$this->driver->getUniqueID();?>" data-list="0" data-src="<?=$this->searchClassId ?>" data-hide-link="<?=($hideLink ? '1' : '0')?>">
    <span class="status ajax-availability hidden">
        <span class="label label-default"><?=$this->transEsc('Loading')?>...</span>
    </span>
</div>
<? endif; ?>
