<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="media-body">
      <div class="media-body-inner">
<!-- Module RecordDriver -->
    <?=$this->render('RecordDriver/SolrDefault/recorddriver-core-title.phtml', ['driver' => $driver]) ?>
<!-- Module RecordDriver -->

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
<!-- Module RecordDriver -->
<?php 
//coreFieldCategory according to category in solrmarc.yaml
$coreFieldCategories = ['title2', 'person', 'description', 'publication', 'rights', 'subject', 'rvk', 'physical', 'related', 'dependentworksbelongsto', 'link', 'internal', 'id'];
?>
<?=$this->render('RecordDriver/SolrDefault/recorddriver-core-data.phtml', ['driver' => $driver, 'coreFieldCategories' => $coreFieldCategories]) ?>
<!-- Module RecordDriver -->
      </div>
      <div class="belugax-item-actions">
          <?=$this->record($this->driver)->getToolbar()?>
          <?
          $QRCode = $this->record($this->driver)->getQRCode("core");
          $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
          $cover = $coverDetails['html'];
          $preview = $this->record($this->driver)->getPreviews();
          ?>
          <? if ($QRCode || $cover || $preview): ?>
              <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
                  <? /* Display qrcode if appropriate: */ ?>
                  <? if($QRCode): ?>
                      <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
                  <? endif; ?>

                  <? // if you have a preview tab but want to move or remove the preview link
                  // from this area of the record view, this can be split into
                  // getPreviewData() (should stay here) and
                  // getPreviewLink() (can go in your desired tab) ?>
                  <? if ($preview): ?>
                      <div class="record-previews">
                          <?=$preview?>
                      </div>
                  <? endif; ?>
              </div>
          <? endif; ?>

      </div>
      <div style="clear: both;">
        <?=$this->context($this)->renderInContext('RecordTab/staffviewmarc', []) ?>
      </div>
  </div>

    <div class="not-found-contact">
        <i class="bel-frage"></i>
        <div class="not-found-message">
            <?=$this->translate("Haven't found what you're looking for?")?>
        </div>
    </div>

</div>
