<div id="DependentWorks" style="">
    <h3><?=$this->transEsc('DependentWorks') ?></h3>
    <div id="DependentWorksRotator">
        <i class="fa fa-spinner"></i>
    </div>
    <ul id="DependentWorks" style="margin-bottom:0px;"></ul>
    <p id="ToggleDependentWorksMore" style="display:none">
        <a href=""><?=$this->transEsc('more') ?></a>
    </p>
    <ul id="DependentWorksHidden" style="margin-top:0px;display:none"></ul>
    <p id="ToggleDependentWorksLess" style="display:none">
        <a href=""><?=$this->transEsc('less') ?></a>
    </p>
</div>