<?php $records = $this->cart()->getRecordDetails(); if (!empty($records)): ?>
  <ul class="is-card-list">
  <?php foreach ($records as $i => $record): ?>
    <li>
      <div class="checkbox">
        <label>
          <?=$this->record($record)->getCheckbox('cart')?>
          <a title="<?=$this->transEscAttr('View Record')?>" href="<?=$this->recordLinker()->getUrl($record)?>" data-lightbox-ignore><?=$this->escapeHtml($record->getTitle())?></a>
        </label>
      </div>
    </li>
  <?php endforeach; ?>
  </ul>
<?php else: ?>
  <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
<?php endif; ?>
