<?php $cart = $this->cart(); ?>
<?php if ($cart->isActive()): ?>
  <?php $cartId = $this->source . '|' . $this->id; ?>
  <span class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a href="#" class="cart-add result-link icon-link hidden<?php if(!$cart->contains($cartId)): ?> correct<?php endif ?>">
      <i class="bel-stern02"></i>
      <span class="icon-link__label"><?=$this->transEsc('Add to Book Bag') ?></span>
    </a>
    <a href="#" class="cart-remove result-link icon-link hidden<?php if($cart->contains($cartId)): ?> correct<?php endif ?>">
      <i class="bel-stern01"></i>
      <span class="icon-link__label"><?=$this->transEsc('Remove from Book Bag') ?></span>
    </a>
  </span>
<?php endif; ?>
