<nav aria-label="<?=$this->transEscAttr('Search Results')?>">
  <ul class="pager hidden-print">
    <?php if ($this->scrollData['previousRecord']): ?>
      <?php if ($this->scrollData['firstRecord']): ?>
        <li role="none">
          <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->scrollData['firstRecord']))?>" aria-label="<?=$this->transEscAttr('First Search Result')?>" rel="nofollow" title="<?=$this->transEsc('First Search Result')?>" data-uk-tooltip>
            <i class="bel-pfeil-r01"></i>
          </a>
        </li>
      <?php endif; ?>
      <li role="none">
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->scrollData['previousRecord']))?>" aria-label="<?=$this->transEscAttr('Previous Search Result')?>" rel="nofollow" title="<?=$this->transEsc('Previous Search Result')?>" data-uk-tooltip>
          <i class="bel-pfeil-r01"></i>
        </a>
      </li>
    <?php else: ?>
      <?php if ($this->scrollData['firstRecord']): ?>
        <li class="disabled" aria-hidden="true" role="none"><a href="#"><i class="bel-pfeil-r01"></i></a></li>
      <?php endif; ?>
      <li class="disabled" aria-hidden="true" role="none"><a href="#"><i class="bel-pfeil-r01"></i></a></li>
    <?php endif; ?>

    <?php if ($this->scrollData['nextRecord']): ?>
      <li role="none">
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->scrollData['nextRecord']))?>" aria-label="<?=$this->transEscAttr('Next Search Result')?>" rel="nofollow" title="<?=$this->transEsc('Next Search Result')?>" rdata-uk-tooltip>
          <i class="bel-pfeil-l01"></i>
        </a>
      </li>
      <?php if ($this->scrollData['lastRecord']): ?>
        <li role="none">
          <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->scrollData['lastRecord']))?>" aria-label="<?=$this->transEscAttr('Last Search Result')?>" rel="nofollow" title="<?=$this->transEsc('Last Search Result')?>" data-uk-tooltip>
            <i class="bel-pfeil-l01"></i>
          </a>
        </li>
      <?php endif; ?>
    <?php else: ?>
      <li class="disabled" aria-hidden="true" role="none"><a href="#"><i class="bel-pfeil-l01"></i></i></a></li>
      <?php if ($this->scrollData['lastRecord']): ?>
        <li class="disabled" aria-hidden="true" role="none"><a href="#"><i class="bel-pfeil-l01"></i></a></li>
      <?php endif; ?>
    <?php endif; ?>
    <li role="none" title="<?=$this->transEsc('Back to Search Results')?>" data-uk-tooltip>
        <?=$this->searchMemory()->getLastSearchLink($this->transEsc('Back'))?>
    </li>
  </ul>

    <?=$this->transEsc('of_num_results', [
        '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
        '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
    ]) ?>
</nav>
