<?php
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->headScript()->appendFile($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ') .
    '<li class="active" aria-current="page">' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?php $sidebarList = $this->related()->getList($this->driver); ?>
  <div class="<?=$this->layoutClass('mainbody')?><?=count($sidebarList) < 1 ? ' solo' : '' ?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource">
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>

    <?php if (count($this->tabs) > 0): ?>
      <a id="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs" role="tablist">
          <?php foreach ($this->tabs as $tab => $obj): ?>
            <?php
              $desc = $obj->getDescription();
              $tabName = preg_replace("/\W/", "-", strtolower($tab));
              $tabClasses = [ 'record-tab', $tabName ];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tabClasses[] = 'active';
                }
                $tabClasses[] = 'initiallyActive';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
            ?>
            <li class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$tabName?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
              <a href="<?=$this->recordLinker()->getTabUrl($this->driver, $tab)?>#tabnav" data-lightbox-ignore>
                <?=$this->transEsc($desc)?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>

        <div class="tab-content">
          <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
    <?php endif; ?>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>':''?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
      <?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
          <?=$this->render('record/prev-next.phtml'); ?>
      <?php endif; ?>

      <div class="availabilityItem" data-id="" data-list="" data-src="" data-hide-link="" data-type="" data-mediatype="">
        <span class="status">
        <h3><?=$this->transEsc('Access and availability')?></h3>
        <div id="paia-availability">
          <div id="daia_results">
            <a name="availability"></a>
              <table>
                <tbody>
                  <tr>
                    <td valign="top">
                      Standort/Signatur: <a href="#" target="_blank">Bibliothek</a><br>
                      <b>1234-5678-90</b><br><span class="daia_green">Präsenznutzung</span><br>
                      nicht ausleihbar
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </span>
      </div>
  </div>
</div>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
