<?php
    // solr data for transfer to prevent further solr requests
    $solrData = $this->driver->formatSolrData();
?>

<div class="availabilityItem <?=$this->additionalClass?>" data-full="<?=$solrData?>" data-id="<?=$this->driver->getUniqueID();?>" data-list="<?=$this->list?>" data-src="<?=$this->driver->getSourceIdentifier(); ?>" data-language="<?=$this->layout()->userLang;?>">
	<span class="status ajax-availability hidden">
        <?=$this->icon('spinner')?>
        <?=$this->transEsc('loading_ellipsis')?>
	</span>
    <?php if (!empty($_GET['debug_ap']) && strip_tags($_GET['debug_ap']) == 'true'): ?>
        <div class="delimiter"></div>
        <a href="<?=$this->url('home')?>AvailabilityPlus/Debug/<?=urlencode($this->driver->getUniqueID());?>?source=<?=$this->driver->getSourceIdentifier();?>&list=<?=$this->list?>" target="_blank"><?=$this->transEsc('AvailabilityPlus::DebugView')?></a>
    <?php endif; ?>
</div>
