<?
// Set up some convenience variables:
$id = $this->driver->getUniqueId();
$source = $this->driver->getSourceIdentifier();
if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
} else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
}

$coverDetails = $this->record($this->driver)->getCoverDetails('result-list', 'medium', $this->recordLinker()->getUrl($this->driver));
$cover = $coverDetails['html'];
$thumbnail = false;
$thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?> belugax-cover">
        <?=$cover ?>
    </div>
    <? $thumbnail = ob_get_contents(); ?>
    <? ob_end_clean(); ?>
<? endif; ?>
<input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>" class="hiddenId" />
<input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource" />
<?=$this->record($this->driver)->getCheckbox()?>
<div class="media">
    <div class="media-left medium belugax-cover">
        <? foreach ($this->driver->getFormats() as $format): ?>
            <? if ($belugino = $this->configreader()->getConfigData('belugino', $format)): ?>
                <i class="<?=$belugino?> belugino-icon-cover" aria-hidden="true" title="<?=$this->transEsc($format) ?>"></i>
            <? else: ?>
                <i class="bel-unbek belugino-icon-cover" aria-hidden="true" title="<?=$this->transEsc($format) ?>"></i>
            <? endif; ?>
        <? endforeach; ?>
    </div>
    <div class="media-body">
        <div class="result-body">
            <div>
                <a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="title getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>">
                    <? if(!empty($this->driver->getShortTitle()[0][0]) && $this->driver->getShortTitle()[0][0] != $this->transEsc('Title not available')) { ?>
                        <?=$this->record($this->driver)->getTitleHtml()?> <? if (!empty($this->driver->getTitleSection()[0][0])) { ?> ; <?=$this->driver->getTitleSection()[0][0]?> <? } ?>
                    <? } else { ?>
                        <? if (!empty($this->driver->getSeries()[0]['name'])) { ?>
                            <?=$this->driver->getSeries()[0]['name']?>
                            <?=' '.$this->driver->getSeries()[0]['number']?>
                        <? } ?>
                    <? } ?>
                </a>
            </div>

            <div>
                <? if($this->driver->isCollection()): ?>
                    <?=implode('<br>', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); ?>
                <? else: ?>
                    <? $summAuthors = $this->driver->getPrimaryAuthorsWithHighlighting(); if (!empty($summAuthors)): ?>
                        <?=$this->transEsc('by')?>
                        <? $authorCount = count($summAuthors); foreach ($summAuthors as $i => $summAuthor): ?>
                            <a href="<?=$this->record($this->driver)->getLink('author', $this->highlight($summAuthor, null, true, false))?>"><?=$this->highlight($summAuthor)?></a><?=$i + 1 < $authorCount ? ',' : ''?>
                        <? endforeach; ?>
                    <? endif; ?>

                    <? $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
                    <? if (!empty($journalTitle)): ?>
                        <?=!empty($summAuthor) ? '<br />' : ''?>
                        <?=$this->transEsc('Published in')?>
                        <? $containerSource = $this->driver->getSourceIdentifier(); ?>
                        <? $containerID = $this->driver->getContainerRecordID(); ?>
                        <? /* TODO: handle highlighting more elegantly here: */?>
                        <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)))?>"><?=$this->highlight($journalTitle) ?></a>
                        <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
                    <? elseif (!empty($summDate)): ?>
                        <?=!empty($summAuthor) ? '<br />' : ''?>
                        <?=$this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0])?>
                    <? endif; ?>

                    <? $summInCollection = $this->driver->getContainingCollections(); if (!empty($summInCollection)): ?>
                        <? foreach ($summInCollection as $collId => $collText): ?>
                            <div>
                                <b><?=$this->transEsc("in_collection_label")?></b>
                                <a class="collectionLinkText" href="<?=$this->url('collection', ['id' => $collId])?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                                    <?=$this->escapeHtml($collText)?>
                                </a>
                            </div>
                        <? endforeach; ?>
                    <? endif; ?>
                <? endif; ?>
            </div>

            <? if(!$this->driver->isCollection()): ?>
                <? if ($snippet = $this->driver->getHighlightedSnippet()): ?>
                    <? if (!empty($snippet['caption'])): ?>
                        <strong><?=$this->transEsc($snippet['caption']) ?>:</strong> ';
                    <? endif; ?>
                    <? if (!empty($snippet['snippet'])): ?>
                        <span class="quotestart">&#8220;</span>...<?=$this->highlight($snippet['snippet']) ?>...<span class="quoteend">&#8221;</span><br/>
                    <? endif; ?>
                <? endif; ?>
            <? endif; ?>

            <?
            /* Display information on duplicate records if available */
            if ($dedupData = $this->driver->getDedupData()): ?>
                <div class="dedupInformation">
                    <?
                    $i = 0;
                    foreach ($dedupData as $source => $current) {
                    if (++$i == 1) {
                        ?><span class="currentSource"><a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->transEsc("source_$source", [], $source)?></a></span><?
                    } else {
                    if ($i == 2) {
                    ?> <span class="otherSources">(<?=$this->transEsc('Other Sources')?>: <?
                        } else {
                            ?>, <?
                        }
                        ?><a href="<?=$this->recordLink()->getUrl($current['id'])?>"><?=$this->transEsc("source_$source", [], $source)?></a><?
                        }
                        }
                        if ($i > 1) {
                        ?>)</span><?
                }?>
                </div>
            <? endif; ?>

            <div class="result-previews">
                <?=$this->record($this->driver)->getPreviews()?>
            </div>
        </div>
        <div class="result-links hidden-print">
            <? /* Display qrcode if appropriate: */ ?>
            <? if ($QRCode = $this->record($this->driver)->getQRCode("results")): ?>
                <?
                // Add JS Variables for QrCode
                $this->jsTranslations()->addStrings(['qrcode_hide' => 'qrcode_hide', 'qrcode_show' => 'qrcode_show']);
                ?>
                <span class="hidden-xs">
          <i class="fa fa-fw fa-qrcode" aria-hidden="true"></i> <a href="<?=$this->escapeHtmlAttr($QRCode);?>" class="qrcodeLink"><?=$this->transEsc('qrcode_show')?></a>
          <div class="qrcode hidden">
            <script type="text/template" class="qrCodeImgTag">
              <img alt="<?=$this->transEsc('QR Code')?>" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
            </script>
          </div><br/>
        </span>
            <? endif; ?>

            <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
            $deleteUrl = null === $list_id
                ? $this->url('myresearch-favorites')
                : $this->url('userList', ['id' => $list_id]);
            $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

            $dLabel = 'delete-label-' . preg_replace('[\W]', '-', $id);
            ?>
            <div class="dropdown">
                <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" href="<?=$deleteUrlGet ?>">
                    <i class="bel-verboten" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
                    <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeJs($id) ?>','source':'<?=$this->escapeJs($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
                    <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
                </ul>
            </div>

            <? /* Hierarchy tree link */ ?>
            <? $trees = $this->driver->tryMethod('getHierarchyTrees'); if (!empty($trees)): ?>
                <? foreach ($trees as $hierarchyID => $hierarchyTitle): ?>
                    <div class="hierarchyTreeLink">
                        <input type="hidden" value="<?=$this->escapeHtmlAttr($hierarchyID)?>" class="hiddenHierarchyId" />
                        <i class="result-link-icon bel-orgaform" aria-hidden="true"></i>
                        <a class="hierarchyTreeLinkText result-link-label" data-lightbox href="<?=$this->recordLink()->getTabUrl($this->driver, 'HierarchyTree')?>?hierarchy=<?=urlencode($hierarchyID)?>#tabnav" title="<?=$this->transEsc('hierarchy_tree')?>" data-lightbox-href="<?=$this->recordLink()->getTabUrl($this->driver, 'AjaxTab')?>?hierarchy=<?=urlencode($hierarchyID)?>" data-lightbox-post="tab=hierarchytree">
                            <?=$this->transEsc('hierarchy_view_context')?><? if (count($trees) > 1): ?>: <?=$this->escapeHtml($hierarchyTitle)?><? endif; ?>
                        </a>
                    </div>
                <? endforeach; ?>
            <? endif; ?>

            <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>':''?>

            <? if ($this->cart()->isActiveInSearch() && $this->params->getOptions()->supportsCart() && $this->cart()->isActive()): ?>
                <div class="belugax-result-badge">
                    <? $cartId = $this->source . '|' . $this->id; ?>
                    <? if ($cart): ?>
                        <?=($cart->contains($cartId)) ? '<i class="bel-stern01">' : '<i>' ?></i>
                    <? endif; ?>
                </div>
            <? endif; ?>

            <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
          but even if we don't plan to display the link, we still want to get the $openUrl
          value for use in generating a COinS (Z3988) tag -- see bottom of file.
        */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

            if ($openUrlActive || !empty($urls)): ?>
                <? if ($openUrlActive): ?>
                    <br/>
                    <?=$openUrl->renderTemplate()?>
                <? endif; ?>
                <? if (!is_array($urls)) $urls = []; ?>
                <? if(!$this->driver->isCollection()): ?>
                    <? foreach ($urls as $current): ?>
                        <? if (strpos($current['desc'], 'Inhaltsverzeichnis') !== false || stripos($current['desc'], 'content') !== false): ?>
                            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="_blank"><i class="bel-inhalt"></i></a>
                        <? endif; ?>
                    <? endforeach; ?>
                <? endif; ?>
            <? endif; ?>

            <!--Module AvailabilityPlus-->
            <?=$this->render('RecordDriver/SolrDefault/availabilityplus-result-list.phtml', ['searchClassId' => $source, 'driver' => $this->driver]) ?>
            <!--Module AvailabilityPlus-->

        </div>
    </div>
</div>
