<?php
    // Set up page title:
    $this->headTitle($this->transEsc('AvailabilityPlus::Availability Plus Debug'));

    $config = $this->config()->get('config');
    $ilsBackends = $config['Catalog']['ilsBackends'] ?? [DEFAULT_SEARCH_BACKEND];
    $sourceCount = count($ilsBackends);
    $source = 'Solr';
    if (isset($_GET['source'])) {
        $source = $_GET['source'];
    } else {
        $source = $ilsBackends[$sourceCount - 1];
    }
    if (isset($_GET['source']) && $_GET['source'] === 'Search2') $source = 'Search2';

    $list = 1;
    if (isset($_GET['list']) && $_GET['list'] === '0') $list = 0;
    $list_name = 'ResultList';
    if ($list == 0) $list_name = 'DetailView';

    // solr data for transfer to prevent further solr requests
    $solrData = $this->driver->formatSolrData();

    $language = $this->layout()->userLang;
    $id = $this->driver->getUniqueID();
    $encodedId = urlencode($id);

    if ($source == 'Search2') {
        $recordRoute = 'Search2Record';
    } else {
        $recordRoute = 'Record';
    }
?>

<div class="AvailabilityPlusDebug">
    <h3><?=$this->transEsc('AvailabilityPlus::Links to Debug Views')?></h3>
    <div>
        <b><?=$source?>:</b>
        <a href="<?=$this->url('home')?>AvailabilityPlus/Debug/<?=$encodedId?>?list=1&source=<?=$source?>">Debug ID <?=$id?> ResultsList Solr</a>
        |
        <a href="<?=$this->url('home')?>AvailabilityPlus/Debug/<?=$encodedId?>?list=0&source=<?=$source?>">Debug ID <?=$id?> DetailView Solr</a>
    </div>
    <div>
        <b>Search2:</b>
        <a href="<?=$this->url('home')?>AvailabilityPlus/Debug/<?=$encodedId?>?list=1&source=Search2">Debug ID <?=$id?> ResultsList Search2</a>
        |
        <a href="<?=$this->url('home')?>AvailabilityPlus/Debug/<?=$encodedId?>?list=0&source=Search2">Debug ID <?=$id?> DetailView Search2</a>
    </div>

    <h3>Debug ID <b><a href="<?=$this->url('home')?><?=$recordRoute?>/<?=$encodedId?>"><?=$this->escapeHtml($id)?></a></b> <?=$list_name?> <?=$source?></h3>
    <div class="availabilityItem" data-full="<?=$solrData?>" data-id="<?=$id?>" data-list="<?=$list?>" data-src="<?=$source?>" data-language="<?=$this->layout()->userLang; ?>" data-debug="1">
        <span class="status ajax-availability hidden">
            <?=$this->icon('spinner')?>
            <?=$this->transEsc('loading_ellipsis')?>
        </span>
    </div>
</div>
