<?php
    // Set up page title:
	$this->headTitle($this->translate('Availability Plus Test Cases'));
	
	//Load Cases
    $specsReader = new \VuFind\Config\SearchSpecsReader();
    $cases = $specsReader->get('availabilityplus-testcases.yaml');
?>
<div class="AvailabilityPlusTestCases">
<? if(!empty($cases)) { ?>
	<table>
		<tr>
			<th>PPN</th>
			<th>Driver</th>
			<th>List</th>
			<th>Description</th>
			<th>Expected</th>
			<th>Result</th>
			<th>Links</th>
			<th>Info</th>
		</tr>
		<? foreach ($cases AS $key => $case) { ?>
		    <?
				$id = $key;
				$driver = $case['driver'];
				$list = $case['list'];
				$description = $case['description'];
				$expected = $case['expected'];
				$reason = $case['reason'];
				$date = $case['date'];
				$creator = $case['creator'];
				$detailsLink = $case['detailsLink'];

                if($driver == 'Search2') {
                    $recordRoute = 'Search2Record';
                    $searchRoute = 'Search2';
                } else {
                    $recordRoute = 'Record';
                    $searchRoute = 'Solr';
                }
			?>
			<tr>
                <td><a href="/vufind/<?=$recordRoute?>/<?=$id?>" target="_blank"><?=$id?></a></td>
				<td><?=$driver?></td>
				<td><?=$list?></td>
				<td><?=$description?></td>
				<td><?=$expected?></td>
				<td>
					<div class="AvailabilityPlusTestCases">
					<?=$this->render('availabilityplus/item.phtml', ['id' => $id, 'driver' => $driver, 'list' => $list, 'mediatype' => $mediatype]) ?>
					</div>
				</td>
                <td>
                    <a href="/vufind/<?=$searchRoute?>/Results?lookfor=id:<?=$id?>" target="_blank">Ergebnislisten-Ansicht</a><br>
                    <a href="/vufind/<?=$recordRoute?>/<?=$id?>" target="_blank">Detail-Ansicht</a><br>
                    <a href="/vufind/AvailabilityPlus/Debug/<?=$id?>?list=<?=$list?>&driver=<?=$driver?>" target="_blank">Debug-Ansicht</a><br>
                </td>
                <td>
                    <? if(!empty($reason)) { ?>
                        Grund: <?=$reason?><br>
                    <? } ?>
                    <? if(!empty($creator)) { ?>
                        Erstellt durch: <?=$creator?><br>
                    <? } ?>
                    <? if(!empty($date)) { ?>
                        Erstellt am: <?=$date?><br>
                    <? } ?>
                    <? if(!empty($detailsLink)) { ?>
                        <a href="detailsLink" target="_blank">Link zu weiteren Details</a><br>
                    <? } ?>
                </td>
            </tr>
			</tr>
		<? } ?>
	</table>
<? } else { ?>
        <div>Keine TestCases definiert</div>
<? } ?>
</div>

