<?php
    // Set up page title:
	$this->headTitle($this->translate('Availability Plus Test Cases'));

	//Load Cases
    $specsReader = new \VuFind\Config\SearchSpecsReader();
    $cases = $specsReader->get('availabilityplus-testcases.yaml');

    // Variables:
    $list = 1;
    if(isset($_GET["list"]) && $_GET["list"] === '0') $list = 0;
    $list_name = 'ResultList';
    if($list == 0) $list_name = 'RecordView';

?>
<div class="AvailabilityPlusTestCases">
<? if(!empty($cases)) { ?>
    <?=$this->transEsc('Links To TestCase Views')?>: <a href="/vufind/AvailabilityPlus/TestCases?list=1"><?=$this->transEsc('TestCases ResultList')?></a> | <a href="/vufind/AvailabilityPlus/TestCases?list=0"><?=$this->transEsc('TestCases RecordView')?></a>
    <h3><?=$this->transEsc('TestCases '.$list_name)?></h3>
    <table>
		<tr>
			<th><?=$this->transEsc('PPN')?></th>
			<th><?=$this->transEsc('Status')?></th>
			<th><?=$this->transEsc('Driver')?></th>
			<th><?=$this->transEsc('Description')?></th>
			<th><?=$this->transEsc('ExpectedResult')?></th>
			<th><?=$this->transEsc('ActualResult')?></th>
			<th><?=$this->transEsc('ViewLinks')?></th>
			<th><?=$this->transEsc('Info')?></th>
		</tr>
		<? foreach ($cases AS $key => $case) { ?>
            <? if(!empty($key) && !empty($case['driver'])) { ?>
                <?
                    $id = $key;
                    $driver = $case['driver'];
                    $description = '';
                    $expected = '';
                    $reason = '';
                    $date = '';
                    $creator = '';
                    $detailsLink = '';
                    $rules = '';

                    if(!empty($case['description'])) $description = $case['description'];
                    if(!empty($case['expected_html'])) {
                        $expected = $case['expected_html'];
                    } else if(!empty($case['expected_description'])) {
                        $expected = $case['expected_description'];
                    }
                    if(!empty($case['reason'])) $reason = $case['reason'];
                    if(!empty($case['date'])) $date = $case['date'];
                    if(!empty($case['creator'])) $creator = $case['creator'];
                    if(!empty($case['detailsLink'])) $detailsLink = $case['detailsLink'];
                    if(!empty($case['rules'])) $rules = $case['rules'];

                    if($driver == 'Search2') {
                        $recordRoute = 'Search2Record';
                        $searchRoute = 'Search2';
                    } else {
                        $recordRoute = 'Record';
                        $searchRoute = 'Search';
                    }
                ?>
                <tr>
                    <td class="testcase_id"><a href="/vufind/<?=$recordRoute?>/<?=$id?>" target="_blank"><?=$id?></a></td>
                    <td class="testcase_status"><span class="testcase_status"></td>
                    <td class="testcase_driver"><?=$driver?></td>
                    <td class="testcase_description"><?=$description?></td>
                    <td class="testcase_expected_result"><?=$expected?></td>
                    <td class="testcase_actual_result"><?=$this->render('availabilityplus/item.phtml', ['id' => $id, 'driver' => $driver, 'list' => $list, 'mediatype' => $mediatype]) ?></td>
                    <td class="testcase_views">
                        <a href="/vufind/<?=$searchRoute?>/Results?lookfor=id:<?=$id?>" target="_blank"><?=$this->transEsc('ResultList')?></a><br>
                        <a href="/vufind/<?=$recordRoute?>/<?=$id?>" target="_blank"><?=$this->transEsc('RecordView')?></a><br>
                        <a href="/vufind/AvailabilityPlus/Debug/<?=$id?>?list=<?=$list?>&driver=<?=$driver?>" target="_blank"><?=$this->transEsc('DebugView')?></a><br>
                    </td>
                    <td class="testcase_infos">
                        <? if(!empty($reason)) { ?>
                            Grund: <?=$reason?><br>
                        <? } ?>
                        <? if(!empty($creator)) { ?>
                            Erstellt durch: <?=$creator?><br>
                        <? } ?>
                        <? if(!empty($date)) { ?>
                            Erstellt am: <?=$date?><br>
                        <? } ?>
                        <? if(!empty($detailsLink)) { ?>
                            <a href="<?=$detailsLink?>" target="_blank"><?=$this->transEsc('link to more details')?></a><br>
                        <? } ?>
                        <? if(!empty($rules)) { ?>
                            <?=$this->transEsc('Checked rule(s)')?>: <?=$rules?><br>
                        <? } ?>
                    </td>
                </tr>
			<? } ?>
		<? } ?>
	</table>
<? } else { ?>
        <div><?=$this->transEsc('no TestCases defined')?></div>
<? } ?>
</div>

