<?php $libraryList = $this->connectedlibraries()->getConnectedLibraries($this->searchClassId, $this->driver); ?>
<?php if (!empty($libraryList)): ?>
<table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
  <tr><th><?=$this->transEsc('Libraries')?>:</th><td>
    <p class="detail-line">
      <? foreach ($libraryList as $library):?>
        <span title="<?=$library['fullname']?>"><?=$library['abbrieviation']?></span> 
      <? endforeach;?>
    </p>
  </td></tr>
</table>
<?php endif; ?>
