<?php
  $this->layout()->sideFacetsInstanceCounter = ($this->layout()->sideFacetsInstanceCounter ?? 0) + 1;
  $this->assetManager()->appendScriptLink('facets.js');

  // Save results/options to $this so they are available to sub-templates:
  $this->results = $results = $this->recommend->getResults();
  $this->options = $options = $results->getOptions();
  $collapsedFacets = $this->recommend->getCollapsedFacets();
  $forceUncollapsedFacets = [];

  // Make sure facets with active selections are not collapsed:
  $filterList = $results->getParams()->getFilterList(true);
  foreach ($filterList as $field => $filters) {
    foreach ($filters as $filter) {
      $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
      if ($index !== false) {
        unset($collapsedFacets[$index]); // Open if we have a match
        $forceUncollapsedFacets[] = $filter['field'];
      }
    }
  }
?>
<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>
<?php
  $checkboxFilters = $this->recommend->getCheckboxFacetSet();
  $hasVisibleCheckboxes = false;
  if (count($checkboxFilters) > 0) {
    foreach ($checkboxFilters as $current) {
      if ($results->getResultTotal() > 0 || $current['alwaysVisible']) {
        $hasVisibleCheckboxes = true;
        break;
      }
    }
  }
?>
<?php if ($results->getResultTotal() > 0 || $hasVisibleCheckboxes): ?>
  <h2><?=$this->transEsc($this->slot('side-facet-caption')->get('Refine Results')) ?></h2>
  <span class="sr-only"><?=$this->transEscAttr('page_reload_on_select_hint') ?></span>
<?php endif; ?>

<?php if ($hasVisibleCheckboxes): ?>
    <div class="checkboxFilter">
      <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
    </div>
<?php endif; ?>

<!-- E-Ressourcenfilter -->
<?php
    $facetField = 'format_facet';
    $facetValue = 'Elektronische Ressource';
    $currentPath = $this->currentPath() . $results->getUrlQuery()->__toString();
    if (strpos($currentPath, $facetField) === false):
        $filterLink   = $this->currentPath() . $results->getUrlQuery()->addFacet($facetField, $facetValue, 'AND');
        $filterText = $this->transEsc('Restrict to e-resources');
        ?>
        <div class="layout_hint button-quick-filter">
            <a href="<?=$filterLink ?>"><strong><?=$this->translate($filterText) ?></strong> <i class="bel-pfeil-l01"></i></a>
        </div>
    <?php
    endif;
?>
<!-- E-Ressourcenfilter -->

<?php
  $checkboxFilters = $this->recommend->getCheckboxFacetSet();
  $hasVisibleCheckboxes = false;
  if (count($checkboxFilters) > 0) {
    foreach ($checkboxFilters as $current) {
      if ($results->getResultTotal() > 0 || $current['alwaysVisible']) {
        $hasVisibleCheckboxes = true;
        break;
      }
    }
  }
?>

<?php $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<?php $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<?php if (!empty($filterList)): ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/filter-list.phtml', [
        'collapsedFacets' => $collapsedFacets,
        'extraFilters' => $extraFilters,
        'filterList' => $filterList,
    ]); ?>
<?php endif; ?>
<?= $this->sideFacetExtraControls ?? '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <?php foreach ($sideFacetSet as $title => $cluster): ?>
    <?php $collapsed = in_array($title, $collapsedFacets); ?>
    <?php // Data-title attribute is for analytics use.  Do not remove. ?>
    <div class="facet-group" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>" data-title="<?=$this->escapeHtmlAttr($cluster['label']) ?>">
      <h3 class="facet-title">
        <button class="title<?php if ($collapsed): ?> collapsed<?php endif ?>" data-bs-toggle="collapse" data-bs-target="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
          <span class="facet-title"><?=$this->transEsc($cluster['label'])?></span>
          <?=$this->icon('collapse', 'facet-title-icon') ?>
        </button>
      </h3>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" role="listbox" class="collapse<?php if (!$collapsed): ?> show<?php endif ?>"<?php if (in_array($title, $forceUncollapsedFacets)): ?> data-force-uncollapsed="1"<?php endif ?>>
        <?=
          $this->context($this)->renderInContext(
              'Recommend/SideFacets/facet.phtml',
              [
                  'facet' => $title,
                  'cluster' => $cluster,
                  'collapsedFacets' => $collapsedFacets,
              ]
          );
        ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?=$this->assetManager()->outputInlineScriptString('registerSideFacetTruncation();');?>
