<? if ($this->cart()->isImsActive()): ?>
<a id="cart-ims-export" class="btn btn-default dropdown-toggle" name="print" title="<?=$this->transEsc('IMS')?>" value="1">
    <i id="cart-ims-export-icon" class="bel-link01"></i>
    <?=$this->transEsc('IMS')?>
</a>
<script type="text/javascript">
    $('#cart-ims-export').on('click', function(e){
        e.preventDefault();
        $('#cart-ims-export-icon').removeClass('bel-link01');
        $('#cart-ims-export-icon').addClass('bel-laden01');
        $('#cart-ims-export-icon').addClass('spinner');
        $.ajax({
            dataType: 'json',
            method: 'POST',
            url: VuFind.path + '/Cart/ims',
            data: { 'imsid': Cookies.getItem('vufind_cart_ims_id'), 'ids': VuFind.cart.getFullItems() }
        })
        .done(function (data) {
            $('#cart-ims-export-icon').removeClass('spinner');
            $('#cart-ims-export-icon').removeClass('bel-laden01');
            $('#cart-ims-export-icon').addClass('bel-link01');
            if (data.imsDownloadUrl) {
                console.log(data);
                //window.location = Cookies.getItem('vufind_cart_ims_url')+'?ims-download='+data.imsDownloadUrl;
            }
        })
    });
</script>
<? endif; ?>