<?
$addThis = $this->addThis();
if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
}
?>
<ul class="record-nav nav nav-pills hidden-print">
    <? if (count($this->driver->getCitationFormats()) > 0): ?>
        <li><a class="cite-record" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Cite')?>" rel="nofollow"><i class="bel-zitat01" aria-hidden="true" data-uk-tooltip title="<?=$this->transEsc('Cite this')?>"></i></a></li>
    <? endif; ?>
    <li><a class="mail-record" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Email')?>" rel="nofollow"><i class="bel-brief01" aria-hidden="true" data-uk-tooltip title="<?=$this->transEsc('Email this')?>"></i></a></li>

    <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <? if(count($exportFormats) > 0): ?>
        <li class="dropdown">
            <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Export')?>" rel="nofollow"><i class="bel-link01" aria-hidden="true" data-uk-tooltip title="<?=$this->transEsc('Export Record')?>"></i></a>
            <ul class="dropdown-menu" role="menu">
                <? foreach ($exportFormats as $exportFormat): ?>
                    <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
                <? endforeach; ?>
            </ul>
        </li>
    <? endif; ?>

    <? $account = $this->auth()->getManager(); ?>
    <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <? if($account->isLoggedIn()): ?>
            <? if ($this->userlist()->getMode() !== 'disabled'): ?>
                <li>
                    <? if ($this->permission()->allowDisplay('feature.Favorites')): ?>
                        <a class="save-record" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Save')?>" rel="nofollow"><i class="bel-speichern" aria-hidden="true" data-uk-tooltip title="<?=$this->transEsc('Add to favorites')?>"></i></a>
                    <? elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
                        <?=$block?>
                    <? endif; ?>
                </li>
            <? endif; ?>
        <? endif; ?>
    <? endif; ?>
    <? if (!empty($addThis)): ?>
        <li><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="bel-stern01" aria-hidden="true" data-uk-tooltip title="<?=$this->transEsc('Bookmark')?>"></i></a></li>
    <? endif; ?>
    <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>
</ul>
