<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <? if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>

      <? // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <? if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <? endif; ?>
    </div>
  <? endif; ?>
  <div class="media-body">
<!-- Module RecordDriver -->
    <?=$this->render('RecordDriver/SolrDefault/core-title.phtml', ['driver' => $driver]); ?>
<!-- Module RecordDriver -->

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <div id="belugax-summary">
        <span id="belugax-summary-preview"><?=$this->truncate($summary, 300)?></span>
        <span id="belugax-summary-full" class="hidden"><?=$summary?></span>
        <? if(strlen($summary) > 300): ?>
          <a id="belugax-summary-toggle"><i class="bel-pfeil-u01"></i></a>
        <? endif; ?>
      </div>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
<!-- Module RecordDriver -->
    <? $coreFieldCategories = []; //coreFieldCategory according to category in solrmarc.yaml ?>
    <?=$this->render('RecordDriver/SolrDefault/core-data.phtml', ['driver' => $driver, 'coreFieldCategories' => $coreFieldCategories]); ?>
<!-- Module RecordDriver -->
<!-- Module DAIA -->
    <?=$this->render('RecordDriver/SolrDefault/daia-core.phtml'); ?>
<!-- Module DAIA -->

    <?=$this->context($this)->renderInContext('RecordTab/staffviewmarc', []) ?>
  </div>
</div>
