<?php
$paiaConfig = parse_ini_file(realpath(getenv('VUFIND_LOCAL_DIR'). '/config/vufind/PAIA.ini'), true);

if($paiaConfig['Global']['usePAIA'] == 1) {
	$isil = $paiaConfig['Global']['isil'];
	$iln = $paiaConfig['Global']['iln'];
	$formats = "";
	$collection_details = array();
	$ppnlink = "";
	$marcField951aValue = "";
	
	if (method_exists($this->driver, 'getFormats')) {
		$formats = $this->driver->tryMethod('getFormats');
	}
	
	if (method_exists($this->driver, 'getCollectionDetails')) {
		$collection_details = $this->driver->tryMethod('getCollectionDetails');
	}
	
	if (method_exists($this->driver, 'getPPNLink')) {
		$ppnlink = $this->driver->tryMethod('getPPNLink');
	}

	if (method_exists($this->driver, 'getMarcRecord')) {
		
		$field_values = array();
		$fields = $this->driver->getMarcRecord()->getFields('912');
		if(!empty($fields) && empty($collection_details)) {
			foreach($fields as $subfield) {
				foreach($subfield->getSubfields('a') as $subfield_content) {
					$field_values[] = $subfield_content->getData();
				}
			}
		}
		$collection_details = $field_values;
		
		$field_values = array();
		$fields = $this->driver->getMarcRecord()->getFields('773');
		if(!empty($fields) && empty($ppnlink)) {
			foreach($fields as $subfield) {
				foreach($subfield->getSubfields('w') as $subfield_content) {
					$field_values[] = $subfield_content->getData();
					break;
				}
			}
		}
		$ppnlink = (empty($field_values[0])) ? '' : $field_values[0];
		$ppnlink = str_replace("(DE-601)","",$ppnlink);
		
		$marcField951aValue = "";
		$marcField951 = $this->driver->getMarcRecord()->getField('951');
		if(!empty($marcField951)) {
			$marcField951aValue = $marcField951->getSubfield('a')->getData();
		}
		
		/*$doi = "";
		$doi = $this->driver->getMarcRecord()->getField('024');
		if(!empty($doi)) {
			$doi = $doi->getSubfield('a')->getData();
		} */
		
		$doi = "";
		$field_values = array();
		$fields = $this->driver->getMarcRecord()->getFields('024');
		if(!empty($fields) && empty($doi)) {
			foreach($fields as $field) {
				if(strpos($field,"_2doi") == true) {
					$doi = $field->getSubfield('a')->getData();
					break;
				}
			}
		}
	}
		
	$daiaPPN = '';
	if ($marcField951aValue == 'MC' || $marcField951aValue == 'ST') {
		$daiaPPN = '';
	} else if ($marcField951aValue == 'AI' && !empty($ppnlink)) {
		$daiaPPN = $ppnlink;
	} else if (empty($daiaPPN) && in_array('Article', $formats, TRUE)) {
		$daiaPPN = "";
	} else 	{
		$daiaPPN = $this->driver->getUniqueID();
	}
	
	if (in_array("GBV_ILN_".$iln ,$collection_details, TRUE) && !empty($daiaPPN)) { ?>
		<div class="daia-availability" data-ppn="<?=$daiaPPN;?>" data-site="<?=$isil?>" data-marcField951aValue="<?=$marcField951aValue?>" data-list="<?=$this->list;?>" data-mediatype="<?=$formats[0]?>"><span class="daia-loading"> <?=$this->transEsc('local_availability_being_determined');?> </span></div>
	<? } else if (($marcField951aValue == 'MC' || $marcField951aValue == 'ST' || $marcField951aValue == 'AI') && $this->list == 1) { ?>
		<div class="delimiter"></div>
		<span style="color: #EB8E12; font-weight: bold;"><?=$this->transEsc('check_volume');?></span>
		➝
		<strong><a href="<?=$this->recordLink()->getUrl($this->driver);?>#availability"><?=$this->transEsc('go_to_detail_view');?></a></strong>
	<? } ?>
	
	<? if (!in_array("GBV_ILN_".$iln,$collection_details, TRUE) || in_array("Article",$formats,true)){ ?>
		<div class="electronic-availability" data-ppn="<?=$this->driver->getUniqueID();?>" data-site="<?=$isil?>" data-openurl="<?=urlencode($this->driver->tryMethod('getOpenURL'));?>" data-url-access="<?=urlencode($url_access);?>" data-url-access-level="<?=$url_access_level;?>" data-first-matching-issn="" data-gvklink="<?=$GVKlink;?>" data-doi="<?=$doi;?>" data-list="<?=$this->list;?>" data-mediatype="<?=$formats[0]?>" style="display:none;"><span class="daia-loading"> <?=$this->transEsc('ft_availability_being_determined');?></span></div>
	<? } ?>

	<?if (empty($daiaPPN) && in_array("GBV_ILN_".$iln,$collection_details, TRUE) && in_array('Article', $formats, TRUE)) {
		if ($this->list == 1) { 
			echo '<div class="delimiter"></div>'; 
		} else {
			echo '<a name="availability"></a>';
			echo'<b>'.$this->transEsc('holdings_and_availability').'</b><br>';
		}
		$containingWorks = $this->driver->tryMethod('getContainingWork');
		if(!empty($containingWorks[0]['ppn'])){
			$record_base_path = substr($this->recordLink()->getUrl($this->driver),0,strrpos($this->recordLink()->getUrl($this->driver),"/")+1);
			echo '<span style="color: #EB8E12; font-weight: bold;">'.$this->transEsc('print_version_available').'</span> - <a target="_blank" class="uncertain_article_access_level" href="'.$record_base_path.$containingWorks[0]['ppn'].'">'.$this->transEsc('to_journal_series').'</a>';
		} else {
			echo '<span style="color: #EB8E12; font-weight: bold;">'.$this->transEsc('print_version_available').'</span> - '.$this->transEsc('to_journal_series');
		}
	}
}
?>
