<footer class="hidden-print">
    <div class="container">
        <div class="footer-container">
            <div class="footer-column">
                <ul>
                    <li><a href="<?=$this->transEsc('link-website')?>" target="_blank"><?=$this->transEsc('Website of the library')?> <i class="bel-pfeil-l01"></i></a></li>
                    <li><a href="<?=$this->transEsc('link-about')?>" target="_blank"><?=$this->transEsc('About the discovery system')?> <i class="bel-pfeil-l01"></i></a></li>
                    <li><a href="<?=$this->transEsc('link-literature')?>" target="_blank"><?=$this->transEsc('Literature')?> <i class="bel-pfeil-l01"></i></a></li>
                </ul>
            </div>

            <div class="footer-column">
                <ul>
                    <li><a href="<?=$this->transEsc('link-contact')?>" target="_blank"><?=$this->transEsc('Contact')?> <i class="bel-pfeil-l01"></i></a></li>
                    <li><a href="<?=$this->transEsc('link-imprint')?>" target="_blank"><?=$this->transEsc('Imprint')?> <i class="bel-pfeil-l01"></i></a></li>
                    <li><a href="<?=$this->transEsc('link-privacy')?>" target="_blank"><?=$this->transEsc('Privacy policy')?> <i class="bel-pfeil-l01"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- Matomo -->
<script type="text/javascript">
    var _paq = window._paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['requireCookieConsent']);
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u="//matomo.qcovery.de/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '13']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<!-- End Matomo Code -->