<div id="bu_fulltext_links_<?echo $this->driver->getUniqueID();?>" style="display:none;">
<?
    //$this->SFX()->buttons()

    $sfx_domains = array('haw', 'hcu', 'hsu', 'tuhh', 'subhh');
    $sfx_domains_display_array = array('haw' => 'HAW', 'hcu' => 'HCU', 'hsu' => 'HSU', 'subhh' => 'UHH', 'tuhh' => 'TUHH');

    $urls = $this->driver->getURLs();

    echo('<!--');
    print_r($urls);
    echo('-->');

    $first = true;
    foreach ($sfx_domains as $sfx_domain) {
        $url = $urls[0]['url'];
        if (stristr($url, '1.1.1.1')) {
            $url = str_ireplace('1.1.1.1?', 'sfx.gbv.de/sfx_'.$sfx_domain.'?', $url);
        } else {
            if (stristr($url, '/sfx_tuhh?')) {
                $url = str_ireplace('/sfx_tuhh?', '/sfx_'.$sfx_domain.'?', $url);
            } else {
                $url = str_ireplace('/sfx_subhh?', '/sfx_'.$sfx_domain.'?', $url);
            }
        }
        if ($sfx_domain == 'tuhh') {
            $url = str_ireplace(':9004', '', $url);
        }
        $result_url_link = $url.'&sfx.service_type';
        $result_url_check_fulltext = $url.'&sfx.service_type=getFullTxt&sfx.response_type=simplexml';
        $issns = $this->driver->getISSNs();
        //echo '<a class="belugaSFXLink bib_button" style="display:none;" data-link="'.urlencode($result_url_check_fulltext).'" data-lookfor="'.$this->driver->getContainerTitle().'" data-institution="'.$institution.'" href="'.$result_url_link.'" target="_blank">';

        echo '<a class="belugaSFXLink button-sfx" style="display:none;" data-link="'.urlencode($result_url_check_fulltext).'" data-lookfor="'.$issns[0].'" data-sfxdomain="'.$sfx_domain.'" data-volume="'.$this->driver->tryMethod('getVolume').'" href="'.$result_url_link.'" target="_blank">';
        echo '<span><i class="sfx-status"></i>'.strtoupper($sfx_domains_display_array[$sfx_domain]).'</span>';
        echo '</a>';
}
?>
</div>
