<?
  // Set up page title:
  $this->headTitle($this->translate('Checked Out Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <? if (!empty($this->transactions)): ?>
    <?=$this->transEsc('checkedout_hints'); ?>
    <? if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals">
      <div class="toolbar">
        <table class="checkbox">
		  <tbody>
		  <tr>
			  <td><label>
				<input type="checkbox" name="selectAll" class="checkbox-select-all"/>
				<?=$this->transEsc('select_page')?>
			  </label></td>
			  <td>
			  <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("extend_loan")?>" />
			  </td>
		  </tr>
		  </tbody>
        </table>
      </div>
    <? endif; ?>

    <? if ($paginator): ?>
      <?
        $end = min(
          $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
          $paginator->getTotalItemCount()
        );
        $transParams = [
          '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
          '%%end%%' => $this->localizedNumber($end),
          '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount())
        ];
      ?>
      <?=$this->translate('showing_items_of_html', $transParams); ?>
    <? endif; ?>

    <? if (is_array($hiddenTransactions)): ?>
      <? foreach ($hiddenTransactions as $ilsDetails): ?>
        <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
          <? $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
          <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
          <? else: ?>
            <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
          <? endif; ?>
        <? endif; ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <? endif; ?>
      <? endforeach; ?>
    <? endif; ?>
	
	<table id="checkedout_data" class="mobile_serialize">
		<thead>
			<tr>
				<th></th>
				<th><?=$this->transEsc('Due Date')?></th>
				<th class="mobile_hide"><?=$this->transEsc('Call Number')?></th>
				<th><?=$this->transEsc('Title');?></th>
				<th class="mobile_hide"><?=$this->transEsc('Renewed')?></th>
				<th class="mobile_hide"><?=$this->transEsc('Reminder')?></th>
			</tr>
		</thead>
    <? $i = 0; foreach ($this->transactions as $resource): ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
	  <tr class="myresearch-result result<?=(++$i % 2 == 0) ? ' alt' : ''?>" id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>">
        <? if ($this->renewForm) { ?>
          <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])) { ?>
            <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
            <td class="checkbox">
              <label>
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
              </label>
              <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            </td>
          <? } else { ?>
			<td data-th = "<?=$this->transEsc('Selection'); ?>"><input type="checkbox" disabled /></td>
		  <? } ?>
        <? } else { ?>
			<td></td>
		<? } ?>

		<td data-th = "<?=$this->transEsc('Due Date'); ?>">
            <? $showStatus = true; ?>

            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <? $showStatus = false; ?>
                <?=$this->escapeHtml($renewDetails['new_date'])?> <? if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><? endif; ?>
                <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
              <? else: ?>
                <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
                <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
              <? endif; ?>
            <? else: ?>
              <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
              <? if ($showStatus): ?>
                <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                  <div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                  <div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
                <? endif; ?>
              <? endif; ?>
            <? endif; ?>

            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <? endif; ?>
         </td>
		 <? if(strpos($ilsDetails['barcode'], ':') && !strpos($ilsDetails['barcode'], ' : ')) {
           $barcode = substr($ilsDetails['barcode'], strpos($ilsDetails['barcode'], ':') + 1);
         } else {
           $barcode = $ilsDetails['barcode'];
         } ?>
         <td class="mobile_hide" data-th = "<?=$this->transEsc('Call Number'); ?>"><?=$this->escapeHtml($barcode) ?></td>
         
		 <td data-th = "<?=$this->transEsc('Title'); ?>">
		 <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLinker()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? if (count($resource->getFormats()) > 0): ?>
              <?=$this->record($resource)->getFormatList() ?>
              <br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>
            <? if ($this->displayItemBarcode && !empty($ilsDetails['barcode'])): ?>
              <strong><?=$this->transEsc('Barcode')?>:</strong> <?=$this->escapeHtml($ilsDetails['barcode'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], [], $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], [], $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>
          </td>
		  
		  <td data-th = "<?=$this->transEsc('Renewed'); ?>" class="mobile_hide">
            <? if (isset($ilsDetails['renew'])): ?>
              <?=$this->transEsc($ilsDetails['renew'])?>
              <? if (isset($ilsDetails['renewLimit'])): ?>
              <? endif; ?>
            <? endif; ?>
			<? if (isset($ilsDetails['renewable']) && !$ilsDetails['renewable']) { 
				$queue = $ilsDetails['queue'];
				if ($queue != 0) {
					echo $this->transEsc('not renewable as recalled');
				} else if ($ilsDetails['renew'] == $ilsDetails['renewLimit']) {
					echo $this->transEsc('not renewable as max renewals reached');
				} else {
					echo $this->transEsc('not renewable');
				}
            } ?>
          </td>
		  
		  <td data-th = "<?=$this->transEsc('Reminder'); ?>" class="mobile_hide">
            <?=$ilsDetails['reminder']; ?>
          </td>
		  
        <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>':''?>
	  </tr>
    <? endforeach; ?>
	</table>
    <? if ($this->renewForm): ?></form><? endif; ?>
    <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
  <? else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
</div>
