<?
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <? if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <? else: ?>
    <table class="table table-striped" summary="<?=$this->transEsc('Your Fines')?>">
    <tr>
      <th><?=$this->transEsc('Fine')?></th>
	  <th><?=$this->transEsc('Date')?></th>
	  <th><?=$this->transEsc('Note')?></th>
      <th><?=$this->transEsc('Fee')?></th>
    </tr>
    <? $totalDue = 0; ?>
    <? foreach ($this->fines as $record): ?>
		<? if(isset($record['amount'])) { ?>
			  <tr>
				<td><?=isset($record['feetype']) ? $this->escapeHtml($record['feetype']) : ''?></td>
				<td><?=isset($record['duedate']) ? $this->escapeHtml($record['duedate']) : ''?></td>
				<td>
				  <? if (empty($record['title'])): ?>
					<?=$this->transEsc('not_applicable')?>
				  <? elseif (!isset($record['driver']) || !is_object($record['driver'])): ?>
					<?=$this->escapeHtml(trim($record['title'], '/:'))?>
				  <? else: ?>
					<a href="<?=$this->recordLink()->getUrl($record['driver'])?>"><?=$this->escapeHtml(trim($record['title'], '/:'))?></a>
				  <? endif; ?>
				</td>
				<td><?=isset($record['amount']) ? $this->safeMoneyFormat($record['amount']) : ''?></td>
			  </tr>
			  <? $totalDue += $record['amount']; ?>
		<? } ?>
    <? endforeach; ?>
      <tr style="font-weight:bold"><td colspan="3"><?=$this->transEsc('Total Balance Due')?></td><td><?=$this->safeMoneyFormat($totalDue) ?></td></tr>
    </table>
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'fines'])?>
</div>
