<?
  // Set up page title:
  $this->headTitle($this->translate('Holds and Interlibrary Loans'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Holds and Interlibrary Loans') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Holds and Interlibrary Loans') ?></h2>

  <?=$this->flashmessages()?>

  <?
      if (isset($_GET['placeHold'])) {
          if ($_GET['placeHold'] == 'success') {
              echo('<div class="message">'.$this->transEsc('placeHoldSuccess').'</div><br/>');
          }
      } 
  ?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>
    
  <?
  if ($this->cancelForm) {
	  $cancel_permitted = true;
  } else {
	  $cancel_permitted = false;
  }
  ?>
  
  <? if (!empty($this->recordList)): ?>
    <?=$this->transEsc('holds_ill_hints'); ?>
    <? if ($cancel_permitted): ?>
      <form name="cancelForm" class="inline" method="post" id="cancelHold">
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
    <? endif; ?>

	<table class="recordSet mobile_serialize">
		<thead>
			<tr>
			<? if ($cancel_permitted): ?>
				<th></th>
			<? endif; ?>
			<th class="mobile_hide"><?=$this->transEsc('Call Number')?></th>
			<th><?=$this->transEsc('Title');?></th>
			<th><?=$this->transEsc('Location');?></th>
			<th><?=$this->transEsc('Remark');?></th>
			</tr>
		</thead>
		
    <? $iteration = 0; ?>
    <? foreach ($this->recordList as $resource): ?>
      <? $iteration++; ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
	  <tr class="myresearch-result result<? if (($iteration % 2) == 0): ?> alt<? endif; ?>" id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>">
        <? if ($cancel_permitted && isset($ilsDetails['cancel_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
          <td>
            <label>
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
            </label>
          </td>
        <? endif; ?>
		
          <? if(strpos($ilsDetails['barcode'], ':') && !strpos($ilsDetails['barcode'], ' : ')) {
            $barcode = substr($ilsDetails['barcode'], strpos($ilsDetails['barcode'], ':') + 1);
          } else {
            $barcode = $ilsDetails['barcode'];
          } ?>
          <td class="mobile_hide" data-th = "<?=$this->transEsc('Call Number'); ?>"><?=$this->escapeHtml($barcode) ?></td>
		  <td data-th = "<?=$this->transEsc('Title'); ?>">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                  . '" class="title">' . $title . '</a>';
              } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo '<span class="title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?></td>

            <!-- Location -->
            <td data-th = "<?=$this->transEsc('Location'); ?>">
              <?=$ilsDetails['location'] ?>
           </td>
			
			<!--- Remarks -->
            <td data-th = "<?=$this->transEsc('Remark'); ?>">
            <? if ($ilsDetails['status'] == 4 ) {?>
                <?=$this->transEsc('collection_required'); ?>
            <? } else if ($ilsDetails['status'] == 2 && (strpos($ilsDetails['title'], 'Fernleihe /') !== false || strpos($title, 'Fernleihe /'))) { ?>
                <?=$this->transEsc('view_in_loan_department'); ?>
            <? } else if ($ilsDetails['status'] == 2) { ?>
                <?=$this->transEsc('ordered'); ?>
            <? } ?>
            </td>
			
            <? if (isset($this->cancelResults['items'])): ?>
              <? foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                  <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
              <div class="text-success"><?=$this->transEsc("hold_available") ?></div>
            <? elseif (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
              <div class="text-success"><?=$this->transEsc('request_in_transit') . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></div>
            <? elseif (isset($ilsDetails['position'])): ?>
              <p><strong><?=$this->transEsc("hold_queue_position") ?>:</strong> <?=$this->escapeHtml($ilsDetails['position']) ?></p>
            <? endif; ?>
            <? if (isset($ilsDetails['cancel_link'])): ?>
              <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
            <? endif; ?>

          <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <? endif ?>
        <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>':''?>
    <? endforeach; ?>
	</table>
    <? if ($cancel_permitted): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any holds placed') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds'])?>
</div>
