<?
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
?>
<h4><?=$this->transEsc('Your Account')?></h4>
<div class="myresearch-menu">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="bel-inhalt" aria-hidden="true"></i> <?=$this->transEsc('Favorites')?>
    </a>
  <? endif; ?>
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <? if ($this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-checkedout')?>"<?=$this->active == 'checkedout' ? ' class="active"' : ''?>>
        <i class="bel-buch" aria-hidden="true"></i> <?=$this->transEsc('Checked Out Items')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-historicloans')?>"<?=$this->active == 'historicloans' ? ' class="active"' : ''?>">
        <i class="bel-lupe" aria-hidden="true"></i> <?=$this->transEsc('Loan History')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-holds')?>"<?=$this->active == 'holds' ? ' class="active"' : ''?>>
        <i class="bel-flagge" aria-hidden="true"></i> <?=$this->transEsc('Holds_Interlibrary_Loans')?>
      </a>
      <!-- <a href="<?=str_replace("Holds","Recalls",$this->url('myresearch-holds'))?>"<?=$this->active == 'recalls' ? ' class="active"' : ''?>>
        <i class="bel-flagge" aria-hidden="true"></i> <?=$this->transEsc('Recalls')?>
      </a> -->
    <? endif; ?>
    <? if ($this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>"<?=$this->active == 'storageRetrievalRequests' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>"<?=$this->active == 'ILLRequests' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?>
    </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-fines')?>"<?=$this->active == 'fines' ? ' class="active"' : ''?>>
        <i class="bel-achtung" aria-hidden="true"></i> <?=$this->transEsc('Fines')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyProfile', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-profile')?>"<?=$this->active == 'profile' ? ' class="active"' : ''?>>
        <i class="bel-idkarte" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
      </a>
    <? endif; ?>
    <? if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>"<?=$this->active == 'librarycards' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
      </a>
    <? endif; ?>
    <?=$this->render('myresearch/delivery-menu.phtml', ['user' => $user]); ?>
  <? endif; ?>
  <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login"<?=$this->active == 'history' ? ' class="active"' : ''?>>
      <i class="bel-lupe" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
  <? endif; ?>
  <? if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>">
      <i class="bel-ausgang" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <? endif; ?>
</div>
<? if ($user && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="myresearch-menu">
    <a href="<?=$this->url('myresearch-changepassword') ?>"<?=$this->active == 'newpassword' ? ' class="active"' : ''?>>
      <i class="bel-schloss02" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
    </a>
  </div>
<? endif; ?>
<? if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="myresearch-menu">
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="bel-inhalt" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>>
        <i class="bel-inhalt" aria-hidden="true"></i> <?=$this->escapeHtml($list['title'])?>
        <span class="badge"><?=$list->cnt ?></span>
      </a>
    <? endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>">
      <i class="bel-plus01" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<? endif ?>
