<?php
// Set up page title:
$this->headTitle($this->translate('My Profile'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

// Only display home library form if we have multiple pickup locations:
$showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);

// Template for use by the renderArray helper:
$arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Your Profile')?></h2>
    <?=$this->flashmessages();?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <table class="table table-striped">
        <?
        $profile = $this->profile;

        $expires = DateTime::createFromFormat('m-d-Y', $profile['expires']);
        $profile['expires'] = $expires->format('d.m.Y');

        echo $this->renderArray(
            $arrTemplate, $profile,
            [
                $this->transEsc('id') => 'id',
                $this->transEsc('Name') => 'name'
            ]
        );
        ?>
        <? if ($showHomeLibForm): ?>
        <tr><th><?=$this->transEsc('Preferred Library')?>:</th>
            <?
            $selected = (isset($this->profile['home_library']) && $this->profile['home_library'] != "")
                ? $this->profile['home_library'] : $this->defaultPickupLocation
            ?>
            <td>
                <form id="profile_form" class="form-inline" method="post">
                    <select id="home_library" name="home_library" class="form-control">
                        <? foreach ($this->pickup as $lib): ?>
                            <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->transEsc('location_' . $lib['locationDisplay'], null, $lib['locationDisplay'])?></option>
                        <? endforeach; ?>
                    </select>
                    <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Save')?>" />
                </form>
            </td>
            <? endif; ?>
            <?php
            echo $this->renderArray(
                $arrTemplate, $profile,
                [
                    /*$this->transEsc('Address') . ' 1' => 'address1',
                    $this->transEsc('Address') . ' 2' => 'address2',
                    $this->transEsc('Zip') => 'zip',
                    $this->transEsc('City') => 'city',
                    $this->transEsc('Country') => 'country',
                    $this->transEsc('Phone Number') => 'phone',
                    $this->transEsc('Mobile Number') => 'mobile_phone',
                    $this->transEsc('Group') => 'group',
                    $this->transEsc('Expires') => 'expiration_date'*/
                    $this->transEsc('Address') => 'address1',
                    $this->transEsc('E-Mail') => 'email',
                    $this->transEsc('Expires') => 'expires',
                    $this->transEsc('Note') => 'note',
                ]
            );
            ?>
    </table>

    <div id="account-barcode">
        <?
        if (isset($profile['username'])) {
            $accountConfig = $this->configreader()->getConfigData('Account');
            if (!empty($accountConfig) && isset($accountConfig['account_barcode_show'])) {
                if ($accountConfig['account_barcode_show']) {
                    $factor = 2;
                    if (isset($accountConfig['account_barcode_factor'])) {
                        $factor = $accountConfig['account_barcode_factor'];
                    }
                    $height = 75;
                    if (isset($accountConfig['account_barcode_height'])) {
                        $height = $accountConfig['account_barcode_height'];
                    }
                    $color = '#000000';
                    if (isset($accountConfig['account_barcode_color'])) {
                        $color = $accountConfig['account_barcode_color'];
                    }
                    $generator = new Picqer\Barcode\BarcodeGeneratorHTML();
                    echo $generator->getBarcode($profile['username'], $generator::TYPE_CODE_39, $factor, $height, $color);
                    echo '<br/>'.$profile['username'];
                }
            }
        }
        ?>
    </div>

    <div id="paiaHint">
        <?= $this->translate('profileHint'); ?>
    </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
