<?php if (sizeof($this->paiaBackends) > 1): ?>
<div class="form-group">
    <label class="control-label" for="login_paia_select"><?=$this->transEsc('PAIA Select')?>:</label>
    <select name="paia-select" id="login_paia_select">
        <?php foreach ($this->paiaBackends as $key => $value): ?>
            <?php
                $selected = false;
                if ($this->request->get('paia-select') == $key) {
                    $selected = true;
                } else if (isset($_GET['doc_id'])) {
                    if (stristr($_GET['doc_id'], $value['docIdPattern'])) {
                        $selected = true;
                    }
                }
            ?>
            <option value="<?=$key?>" <?php if($selected): ?>selected="selected"<?php endif; ?>><?=$value['name']?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>