<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('History') . '</li>';

  $saveSupported = $this->accountCapabilities()->getSavedSearchSetting() === 'enabled';
?>

<div class="<?=$this->layoutClass('mainbody')?> mainbody-full">
  <?=$this->flashmessages()?>
  <? if ($saveSupported && !empty($this->saved)): ?>
    <h2><?=$this->transEsc("history_saved_searches")?></h2>
    <?=$this->context()->renderInContext('search/history-table.phtml', ['showSaved' => true]);?>
  <? endif; ?>

  <h2><?=$this->transEsc("history_recent_searches")?></h2>
  <? if (!empty($this->unsaved)): ?>
    <?=$this->context()->renderInContext('search/history-table.phtml', ['showSaved' => false]);?>
    <a href="?purge=true"><i class="bel-verboten" aria-hidden="true"></i> <?=$this->transEsc("history_purge")?></a>
  <? else: ?>
    <?=$this->transEsc("history_no_searches")?>
  <? endif; ?>
</div>
