<?
  // Set up page title:
  $this->headTitle($this->translate('Delivery Edit'));

  $deliverUser = $this->deliveryUser;
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('delivery-home') . '">' . $this->transEsc('Delivery Home') . '</a></li><li class="active">' . $this->transEsc('Delivery Edit') . '</li>';
  if ($deliverUser['is_admin'] == 'y'):
    $this->layout()->breadcrumbs .= '<li><a href="' . $this->url('delivery-admin') . '">' . $this->transEsc('Delivery Admin') . '</a></li> ';
  endif;
?>

<h2 class="lightbox-header"><?=$this->transEsc('Delivery Edit')?></h2>
<?=$this->flashmessages()?>

<form action="<?=$this->url('delivery-edit') ?>" method="post" name="deliveryEditForm" class="form-login">
  <input type="hidden" name="update" value="y" />
  <div class="form-group">
    <label class="control-label" for="card_number"><?=$this->transEsc('Card Number') ?></label>
    <input class="form-control" type="text" name="card_number" value="<?=$this->deliveryUser['card_number'] ?>" />
  </div>
  <div class="form-group">
    <label class="control-label" for="delivery_email"><?=$this->transEsc('Email') ?></label>
    <input class="form-control" type="text" name="delivery_email" value="<?=$this->deliveryUser['delivery_email'] ?>" />
  </div>
  <div class="form-group">
    <input class="btn btn-primary" name="submit" value="<?=$this->transEsc('Save') ?>" type="submit">
  </div>
</form>

