<?php

  // Set up page title:
  $this->headTitle($this->translate('Delivery Home'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Delivery Home') . '</li><li><a href="' . $this->url('delivery-edit') . '">' . $this->transEsc('Delivery Edit') . '</a></li>';
  if ($deliverUser['is_admin'] == 'y'):
    $this->layout()->breadcrumbs .= '<li><a href="' . $this->url('delivery-admin') . '">' . $this->transEsc('Delivery Admin') . '</a></li> ';
  endif;
?>

<div class="<?=$this->layoutClass('mainbody')?>">
    <h2 class="lightbox-header"><?=$this->transEsc('Delivery Home')?></h2>
    <h3><?=$this->name?></h3>
    <?=$this->message?>

</div>
<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'delivery'])?>
</div>


