<?php
  // Set up page title:
  $this->headTitle($this->translate('Delivery List'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Delivery Home') . '</li><li><a href="' . $this->url('delivery-edit') . '">' . $this->transEsc('Delivery Edit') . '</a></li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
    <h2 class="lightbox-header"><?=$this->transEsc('Delivery List')?></h2>
<?php if (!empty($this->error)): ?>
    <?=$this->transEsc($this->error) ?>
<?php endif; ?>
    
<?php if (!empty($this->message) && $this->message != 'authorized'): ?>
    <?=$this->transEsc('You are not authorized to use our delivery service.') ?>
<?php else: ?>
    <p><a href="<?=$this->url('delivery-home')?>"><?=$this->transEsc('View delivery home') ?></a></p>
    <?php if (count($this->listData) > 0): ?>
    <table class="recordSet mobile_serialize">
      <thead>
        <tr>
            <th><?=$this->transEsc('Title') ?></th>
<!--            <th><?=$this->transEsc('Author') ?></th>
            <th><?=$this->transEsc('Year') ?></th>//-->
            <th><?=$this->transEsc('order_id') ?></th>
            <th><?=$this->transEsc('Status') ?></th>
            <th><?=$this->transEsc('Date') ?></th>
            <th><?=$this->transEsc('Comment') ?></th>
        </tr>
      </thead>
      <tbody>
<?php foreach ($this->listData as $listItem): ?>
    <?php $status = (!empty($listItem['rejected'])) ? 'rejected' : (!empty($listItem['delivered'])) ? 'delivered' : 'ordered'; ?>
        <tr>
            <td><a href="/vufind/Record/<?=$listItem['record_id'] ?>"><?=$listItem['title'] ?></a></td>
<!--            <td><?=$listItem['author'] ?></td>
            <td><?=$listItem['year'] ?></td>//-->
            <td><?=$listItem['order_id'] ?></td>
            <td><?=$this->transEsc($status) ?></td>
            <td><?=$listItem[$status] ?></td>
            <td><?=$listItem['comment'] ?></td>
        </tr>
      </tbody>
<?php endforeach; ?>
    </table>
    <?php else: ?>
    <p><?=$this->transEsc('Your delivery list is empty.') ?></p>
    <?php endif; ?>
<?php endif; ?>

</div>
<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'delivery'])?>
</div>


