<?php
  // Set up page title:
  $this->headTitle($this->translate($this->title) . ' ' . $this->translate('Order'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc($this->title) . ' ' . $this->transEsc('Order') . '</li><li><a href="' . $this->url('delivery-home') . '">' . $this->transEsc('Delivery Home') . '</a></li>';

  $errors = $this->errors;
  $missingFields = $this->missingFields;
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2 class="lightbox-header"><?=$this->transEsc($this->title) . ': ' . $this->transEsc('Order')?></h2>
  <?php if (!empty($errors)): ?>
  <p>
    <?php foreach ($errors as $error): ?>
    <?=$this->transEsc($error) ?><br />
    <?php endforeach; ?>
  </p>
  <?php endif; ?>

<?php //print_r($missingFields); ?>

<?php if (!empty($this->orderId)): ?>
  <p><?=$this->transEsc('Your Order is Placed') ?></p>
<?php else: ?>
  <form method="post" action="<?=$this->url('delivery-order')?>" name="deliveryRegisterForm" class="form-order">
    <input type="hidden" name="update_email" value="y" />
    <input type="hidden" name="domain" value="<?=$this->domain ?>" />
    <input type="hidden" name="searchClassId" value="<?=$this->searchClassId ?>" />
  <?php if (!empty($this->selectFormats)): ?>
    <div class="form-group">
      <label class="control-label" for="format"><?=$this->transEsc('Format') ?></label>
      <select name="format" id="format" class="form-control">
      <?php foreach ($this->selectFormats as $selectFormat): ?>
        <option value="<?=$selectFormat ?>"><?=$this->transEsc($selectFormat) ?></option>
      <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="sendForm" value="<?=$this->transEsc('Send')?>">
    </div>
  <?php else: ?>
    <input type="hidden" name="order" value="y" />
    <input type="hidden" name="id" value="<?=$this->id ?>" />
    <?php foreach ($this->forms as $form): ?>
      <?php if (!empty($form['title'])): ?>
    <div class="form-group">
      <h3><?=$this->transEsc($form['title']) ?></h3>
    </div>
      <?php endif; ?>
      <?php if ($form['type'] == 'input'): ?>
        <?php foreach ($form['fields'] as $field): ?>
          <?php $mandatory = ($field['mandatory'] == 1) ? ' *' : ''; ?>
          <?php $style = (in_array($field['form_name'], $missingFields)) ? ' style="color:red"' : ''; ?>
          <?php $placeholder = (!empty($field['placeholder'])) ? ' placeholder="' . $field['placeholder'] . '"' : ''; ?>
    <div class="form-group">
      <label class="control-label" for="<?=$field['form_name'] ?>"<?=$style ?>><?=$this->transEsc($field['display']) ?><?=$mandatory ?></label>
      <input type="text" name="<?=$field['form_name'] ?>" id="<?=$field['form_name'] ?>" value="<?=$field['value'] ?>"<?=$placeholder ?> class="form-control"/>
    </div>
        <?php endforeach; ?>
      <?php endif; ?>
      <?php if ($form['type'] == 'checkbox'): ?>
        <?php foreach ($form['fields'] as $field): ?>
    <div class="form-group">
      <label class="control-label" for="<?=$field['form_name'] ?>"><?=$this->transEsc($field['display']) ?></label>
      <input type="checkbox" name="<?=$field['form_name'] ?>" id="<?=$field['form_name'] ?>" value="<?=$field['form_value'] ?>" style="margin: 0px 10px 0px; vertical-align:middle;"/>
    </div>
        <?php endforeach; ?>
      <?php endif; ?>
      <?php if ($form['type'] == 'text'): ?>
        <?php foreach ($form['fields'] as $field): ?>
          <?php if (!empty($field['value'])): ?>
    <div class="form-group">
      <p><strong><?=$this->transEsc($field['display']) ?>:</strong> <?=$this->transEsc($field['value']) ?></p>
      <input type="hidden" name="<?=$field['form_name'] ?>" value="<?=$field['value'] ?>"/>
    </div>
          <?php endif; ?>
        <?php endforeach; ?>
      <?php endif; ?>
    <?php endforeach; ?>

    <div class="form-group">
      <h3><?=$this->transEsc('User Data') ?></h3>
    </div>
    <div class="form-group">
      <p><strong><?=$this->transEsc('Name') ?>:</strong> <?=$this->name ?></p>
    </div>
    <div class="form-group">
      <p><strong><?=$this->transEsc('Catalog Id') ?>:</strong> <?=$this->catalog_id ?></p>
    </div>
    <div class="form-group">
      <p>
          <?php $style = (in_array('delivery_email', $missingFields)) ? ' style="color:red"' : ''; ?>
          <label class="control-label" for="delivery_email"<?=$style ?>><?=$this->transEsc('Delivery Email') ?>: *</label>
          <input type="text" name="delivery_email" id="email" value="<?=$this->delivery_email ?>" style="width:380px;"/>
      </p>
    </div>

    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="sendForm" value="<?=$this->transEsc('Order')?>">
      <input class="btn btn-primary" type="reset" name="resetForm" value="<?=$this->transEsc('Reset')?>">
    </div>
  <?php endif; ?>
  </form>
<?php endif; ?>

</div>
