<? foreach ($this->HelpTooltips()->getHelpTooltipsConfig($context) as $helpTooltip):?>
    <span class="<?=$helpTooltip['class']?>" data-helpContent="<?=$this->transEsc($helpTooltip['translation'])?>" data-help_my_position="<?=$helpTooltip['my_position']?>" data-help_at_position="<?=$helpTooltip['at_position']?>" data-target="<?=$helpTooltip['target']?>" data-x="<?=$helpTooltip['x']?>" data-y="<?=$helpTooltip['y']?>" style="display:none"></span>
<? endforeach; ?>
<script type="text/javascript">
    <? if ($showHelp = $this->HelpTooltips()->showHelp()) : ?>
    window.showHelp = true;
    <? else: ?>
    window.showHelp = false;
    <? endif; ?>

    $( document ).ajaxComplete(function() {
        $('.showHelp').qtip('reposition');
        console.log( "Repositioned HelpToolTips due to ajaxComplete" );
    });
</script>
