<?php if ($this->authenticator()->isAuthorized()): ?>
    <?php if ($this->availabilitychecker()->check($this->driver) == 'available'): ?>
        <a href="<?=$this->url('delivery-order') ?>?id=<?=$this->driver->getUniqueId() ?>&searchClassId=<?=$this->searchClassId ?>" aria-expanded="false" data-uk-tooltip="<?=$this->transEsc('Deliver')?>" title="<?=$this->transEsc('Deliver')?>"><i class="bel-ok03" aria-hidden="true"></i></a>
    <?php else: ?>
        <?php $hierarchyTopId = $this->availabilitychecker()->getHierarchyTopID($this->driver); ?>
        <?php if (!empty($hierarchyTopId)): ?>
        <span class="delivery_article" data-top-id="<?=$hierarchyTopId ?>" data-searchclass-id="<?=$this->searchClassId ?>" style="display:none">
            <a href="<?=$this->url('delivery-order') ?>?id=<?=$this->driver->getUniqueId() ?>&searchClassId=<?=$this->searchClassId ?>" aria-expanded="false" data-uk-tooltip="<?=$this->transEsc('Deliver')?>" title="<?=$this->transEsc('Deliver')?>"><i class="bel-ok03" aria-hidden="true"></i></a>
        </span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
