<h1>Hilfe zur erweiterten Suche</h1>

<ul class="HelpMenu">
  <li><a href="#Search Fields">Suchfelder</a></li>
  <li><a href="#Search Groups">Suchgruppen</a></li>
  <li><a href="#Example">Beispiel</a></li>
</ul>

<dl class="Content">
  <dt><a name="Search Fields"></a>Suchfelder</dt>
  <dd>
    <p>
        Wählen Sie über das Pulldown-Menü aus, wonach Sie suchen möchten (z.B. Titel, Autor*in).
        Unter "Suchbedingung" können Sie die einzelnen Felder innerhalb einer Suchgruppe miteinander
        kombinieren:
    </p>
    <ul>
        <li>
            "Und" - Gibt nur die Treffer zurück, die alle Wörter bzw. Phrasen aus dieser Suchgruppe
            enthalten.
        </li>
        <li>
            "Oder" - Gibt die Treffer zurück, die mindestens eines der Wörter oder Phrasen aus dieser
            Suchgruppe enthalten.
        </li>
        <li>
            "Und nicht" - Gibt alle Treffer zurück, die nicht in dieser Suchgruppe angegebenen Wörter
            oder Phrasen enthalten. Diese Suchbedingung funktioniert nur bei der Suche mit mindestens
            zwei Suchgruppen.
        </li>
    </ul>
  </dd>
  
  <dt><a name="Search Groups"></a>Suchgruppen</dt>
  <dd>
    <p>
        Manche Suchanfragen sind komplizierter und eine Suche über verschiedene Felder reicht nicht aus.
        Mit Suchgruppen können Sie Suchfelder zu einer Suche gruppieren: Mit "Mit ALLEN Suchgruppen"
        oder "Mit IRGENDEINER Suchgruppe" können Sie die Suchgruppen mit „und“ oder „oder“
        verknüpfen.
    </p>
  </dd>

    <dt><a name="Example"></a>Beispiel</dt>
    <dd>
        <p>
            Sie wollen nach Titeln zur Stadtsoziologie in Deutschland und zur Stadtsoziologie Chinas suchen:
        </p>
        <ul>
            <li>
                Fügen Sie in die Eingabefelder der ersten Suchgruppe die Begriffe „Deutschland“ und „China“
                ein und setzen Sie "Suchbedingung" auf "oder".
            </li>
            <li>
                Fügen Sie eine weitere Suchgruppe hinzu und geben Sie dort "Stadtsoziologie" ein.
            </li>
            <li>
                Setzen Sie die Suchbedingung auf "Mit ALLEN Suchgruppen".
            </li>
        </ul>
    </dd>
</dl>
