<? $cart = $this->cart(); ?>
<? if ($cart->isActive()): ?>
  <? $cartId = $this->source . '|' . $this->id; ?>
  <span class="btn-bookbag-toggle belugax-result-list-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <button class="cart-add hidden<? if(!$cart->contains($cartId)): ?> correct<? endif ?>">
      <i class="cart-link-icon bel-stern02" title="<?=$this->transEsc('Add to Book Bag') ?>"></i><!--
   --><span class="cart-link-label"><?=$this->transEsc('Add to Book Bag') ?></span><!--
 --></button>
    <button class="cart-remove hidden<? if($cart->contains($cartId)): ?> correct<? endif ?>">
      <i class="cart-link-icon bel-stern01" title="<?=$this->transEsc('Remove from Book Bag') ?>"></i><!--
   --><span class="cart-link-label"><?=$this->transEsc('Remove from Book Bag') ?></span>
    </button>
    <noscript>
      <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
        <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
        <? if ($cart->contains($cartId)): ?>
          <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
        <? else: ?>
          <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
        <? endif; ?>
      </form>
    </noscript>
  </span>
<? endif; ?>
