<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
        <? if ($this->permission()->allowDisplay($tab['permission'])): ?>
          <li<?=$tab['selected'] ? ' class="active"' : ' class="searchTabResultCount" data-searchclass="' . $tab['class'] . '" data-query=' . json_encode(strval($this->query)) . ' '?>>
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?><?=$tab['selected'] ? ' (' . number_format($this->recordTotal, 0, ',', '.') . ')' : ''?></a>
          </li>
        <? elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
        <? endif; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
