<div id="electronic-availability">
<?
	$list = $_GET['list'];
	
	$e_availability = $this->paia()->getElectronicAvailability($_GET['ppn'], urldecode($_GET['openurl']), urldecode($_GET['url-access']),$_GET['url-access-level'], $_GET['first-matching-issn'], $_GET['gvklink'],$_GET['doi'],urldecode($_GET['requesturi']), $_GET['list']);
	
	echo '<div style="display:none;">';
		print_r($e_availability);
	echo '</div>';
	
	if ($e_availability) {
		if($list == 1) {
			if($e_availability['list']['url_access']) {
				$url_access = $e_availability['list']['url_access'];
				$url_access_level = $e_availability['list']['url_access_level'];
				$url_access_label = $e_availability['list']['url_access_label'];
				$doi = $e_availability['list']['doi'];
				
				echo '<div class="delimiter"></div>';
				echo '<h6>';
				echo '<a target="_blank" href="'.$url_access.'" class="'.$url_access_level.'">'.$this->transEsc($url_access_label).' '.$this->transEsc($url_access_level).'</a>';
				if ($doi) { ?>
					<span class="doi"><?=$doi;?></i>
				<? }
				echo '</h6>';
			}
		} else {
			if(!empty($e_availability['list']['url_access'])) {
				$access_notification = array();
				foreach ($e_availability['items'] as $link) {
					if($link['url_access']) {
						$url_access = $link['url_access'];
						$url_access_level = $link['url_access_level'];
						$url_access_label = $link['url_access_label'];
						$doi = $link['doi'];
						
						if($link['access_notification']) {
							$access_notification[] = $link['access_notification'];
						}
						
						echo '<a target="_blank" href="'.$url_access.'" class="'.$url_access_level.'">'.$this->transEsc($url_access_label).' '.$this->transEsc($url_access_level).'</a>';
						if ($doi) { ?>
							<span class="doi"><?=$doi;?></i></span>
						<? }
						echo '</br>';
					}
				}
				
				$access_notification = array_unique($access_notification);
				foreach ($access_notification as $notification) {
					echo $notification;
				}
			} else {
				echo $e_availability['list']['url_access_label'];
			}
		}
	}
	

?>
</div>