<div id="electronic-availability">
<?
	$list = $_GET['list'];
	$language = $this->layout()->userLang;
	
	$e_availability = $this->paia()->getElectronicAvailability($_GET['ppn'], urldecode($_GET['openurl']), urldecode($_GET['url-access']),$_GET['url-access-level'], $_GET['gvklink'],$_GET['doi'], $list, $_GET['mediatype'], $language);
	
	echo '<div style="display:none;">';
		print_r($e_availability);
	echo '</div>';
	
	if ($e_availability) {
		if($list == 1) {
			if($e_availability['list']['url_access']) {
				$url_access = $e_availability['list']['url_access'];
				if(is_array($url_access)) {
					$url_access = $url_access[0];
				}
				$url_access_level = $e_availability['list']['url_access_level'];
				$url_access_label = $e_availability['list']['url_access_label'];
				$doi = $e_availability['list']['doi'];
				
				echo '<div class="delimiter"></div>';
				echo '<span>';
				echo '<a target="_blank" href="'.$url_access.'" class="'.$url_access_level.'">'.$this->transEsc($url_access_label).'</a>';
				if ($doi) { ?>
					<span class="doi"><?=$doi;?></i>
				<? }
				echo '</span>';
			}
		} else {
			if(!empty($e_availability['list']['url_access'])) {
				$access_notification = array();
				echo '<a name="availability"></a>';
				echo'<b>'.$this->transEsc('electronic_availability').'</b><br>';
				foreach ($e_availability['items'] as $link) {
					if($link['url_access']) {
						$url_access = $link['url_access'];
						if(is_array($url_access)) {
							$url_access = $url_access[0];
						}
						$url_access_level = $link['url_access_level'];
						$url_access_label = $link['url_access_label'];
						$doi = $link['doi'];
						
						if($link['access_notification']) {
							$access_notification[] = $link['access_notification'];
						}
						
						echo '<a target="_blank" href="'.$url_access.'" class="'.$url_access_level.'">'.$this->transEsc($url_access_label).'</a>';
						if ($doi) { ?>
							<span class="doi"><?=$doi;?></i></span>
						<? }
						echo '</br>';
					}
				}
				
				$access_notification = array_unique($access_notification);
				foreach ($access_notification as $notification) {
					echo $notification;
				}
			} else {
				echo $e_availability['list']['url_access_label'];
			}
		}
	} else if (!$e_availability && $list != 1 ) {
		echo $this->transEsc('no_electronic_availability');
	}
	

?>
</div>