<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <? if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>

      <? // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <? if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <? endif; ?>
    </div>
  <? endif; ?>
  <div class="media-body">
<!-- Module RecordDriver -->
    <?=$this->render('RecordDriver/DefaultRecord/recorddriver-core-title.phtml', ['driver' => $driver]) ?>
<!-- Module RecordDriver -->

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
<!-- Module RecordDriver -->
<?php 
//coreFieldCategory according to category in solrmarc.yaml
$coreFieldCategories = ['title2', 'person', 'publication', 'subject', 'description', 'related'];
?>
<?=$this->render('RecordDriver/DefaultRecord/recorddriver-core-data.phtml', ['driver' => $driver, 'coreFieldCategories' => $coreFieldCategories]) ?>
<!-- Module RecordDriver -->
<!-- Module Libraries -->
<?=$this->render('RecordDriver/DefaultRecord/libraries-core.phtml', ['searchClassId' => $this->searchClassId, 'driver' => $this->driver]) ?>
<!-- Module Libraries -->
<!-- Module DAIA -->
    <?//=$this->context($this)->renderInContext('RecordDriver/SolrDefault/daia-check.phtml', ['list' => '0']); ?>
<!-- Module DAIA -->
<!-- Module DependentWorks -->
    <?=$this->render('RecordDriver/DefaultRecord/dependentworks-core.phtml') ?>
<!-- Module DependentWorks -->
    <?=$this->context($this)->renderInContext('RecordTab/staffviewmarc', []) ?>
  </div>
</div>
