<?php
    echo '<button class="accordion">'.$debug['check'];
    if(!empty($debug['SolrMarcKey']) && $debug['check'] !== $debug['SolrMarcKey']) echo ' - SolrMarcKey: '.$debug['SolrMarcKey'];
    if(!empty($debug['status'])) echo ' - <span class="'.$debug['status']['level'].'">'.$this->transEsc($debug['status']['label']).'</span>';
    echo '</button>';

    echo '<div class="panel">';
    print "<pre>";
    print_r($debug);
    print "</pre>";
    echo '</div>';
?>
<script>
    /*var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    } */
</script>
