<?php

$services = [];

foreach($data->document[0]->item as $result) {
        $services[$result->availabilityplus->daia->service][] = $result->availabilityplus;
        if(empty($services[$result->availabilityplus->daia->service]['score'])) {
            $services[$result->availabilityplus->daia->service]['score'] = $result->availabilityplus->score;
        } else {
            if($services[$result->availabilityplus->daia->service]['score'] > $result->availabilityplus->score) {
                $services[$result->availabilityplus->daia->service]['score'] = $result->availabilityplus->score;
            }
        }
}

uasort($services, function($a, $b) {
    return $a['score'] <=> $b['score'];
});

$break = false;
foreach($services as $service_label => $service_items) {

    if(!in_array($service,array('openaccess','remote')) || !in_array($mode, ['break_on_first','break_on_first_next'])) {
        echo '<div class="service_group">'.$this->translate($service_label).'</div>';
    }

    foreach($service_items as $key => $result) {
        if(!empty($result)) {
            echo '<div class="delimiter"></div>';
            if(!$list) echo '<div class="daia_item">';
        }
        echo '<div class="daia_storage_callnumber">';
        if(!empty($result->storage)) {
            if(!empty($result->storage->url)) {
                echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$result->storage->url.'" class="'.$result->storage->level.'" title="'.$result->storage->label.'" target="_blank">'.$this->translate($result->storage->label).'</a></span>';
            } else {
                echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').'</span> '.$this->translate($result->storage->label).'</span>';
            }

        }
        if(!empty($result->callnumber)) {
            echo ' <span class="item_label">' . $result->callnumber . '</span>';
        }
        echo '</div>';
        if(!empty($result->daia_hint)) {
            echo '<span class="daia_hint"><span class="'.$result->daia_hint->level.'">'.$this->translate($result->daia_hint->label);
            if(!empty($result->daia_hint->label_date)) echo ' '.$result->daia_hint->label_date;
            echo '</span></span>';
        }
        if(!empty($result->daia_hint) && !empty($result->daia_action)) {
            echo '<span class="daia_arrow"> ➝ </span>';
        }
        if(!empty($result->daia_action)) {
            if(!empty($result->daia_action->url)) {
                echo '<span class="daia_action"><a href="'.$result->daia_action->url.'" class="'.$result->daia_action->level.' link_external" title="'.$result->daia_action->label.'" target="_blank">'.$this->translate($result->daia_action->label).'</a></span>';
            } else {
                echo '<span class="daia_action">'.$this->translate($result->daia_action->label).'</span>';
            }
        }
        if(!$list){
            if(!empty($result->queue)) {
                echo '<div class="service_queue">'.$result->queue->length.' '.$this->translate($result->queue->label).'</div>';
            }
            if(!empty($result->about)) {
                echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.$result->about.'</div>';
            }
            if(!empty($result->chronology)) {
                echo '<div class="item_chronology"><span class="item_chronology_prefix">'.$this->translate('Inventory Information').': </span>'.$result->chronology.'</div>';
            }
        }
        if(!empty($result)) {
            if($list && count($data->document[0]->item) > 1 && !empty($result->storage)) {

                if($this->source == 'Search2') {
                    $recordRoute = 'Search2Record';
                } else {
                    $recordRoute = 'Record';
                }

                echo '<div class="additional_copies"><a href="/vufind/'.$recordRoute.'/'.$id.'">'.$this->transEsc('additional_copies').'...</a></div>';
            }
            if(!$list) echo '</div>';
        }
        if(in_array($mode, ['break_on_first','break_on_first_next'])) {
            $break = true;
            break;
        }
    }
    if($break) break;
}

?>