<?php
$level_org = $level;
$label_org = $label;

echo $url;

$data = json_decode($data);

foreach($data->document[0]->item as $item) {
    $services['openaccess'] = [];
    $services['remote'] = [];
    $services['loan'] = [];
    $services['presentation'] = [];
    $services['interloan'] = [];
    //TODO: default services not available

    foreach($item->available as $service) {
        $services[$service->service] = $service;
    }

    if(empty($services)){
        foreach($item->unavailable as $service) {
            if(count(get_object_vars($service)) > 1) {
                $services[$service->service] = $service;
            }
        }
    }

    foreach($services as $service) {
        if(!empty($service)) {
            //TODO: switch case for service templates
            print_r($service);
            break;
        }
    }


}


?>