<?php
$data = json_decode($data);

foreach($data->document[0]->item as $item) {

    $item_services['available']['openaccess'] = [];
    $item_services['available']['remote'] = [];
    $item_services['available']['loan'] = [];
    $item_services['available']['presentation'] = [];
    $item_services['available']['fallback'] = 'fallback';

    foreach($item->available as $service) {
        $item_services['available'][$service->service] = $service;
    }

    foreach($item->unavailable as $service) {
        if(count(get_object_vars($service)) > 1) {
            $item_services['available'][$service->service] = $service;
        }
    }

    $break = false;
    foreach($item_services['available'] as $service_key=>$service_content) {
        $level='';
        $label='';
        $url='';
        $limitation='';
        if(!empty($service_content)) {
            if($mode == 'break_on_first') {
                $break = true;
            }
            switch($service_key) {
                case 'openaccess':
                    $level = 'FreeAccess link_external';
                    $label = 'FreeAccess';
                    $url = $service_content->href;
                    echo '<div class="delimiter"></div>';
                    echo '<a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a><br/>';
                    break;
                case 'remote':
                    $level = 'LicensedAccess link_external';
                    $label = 'LicensedAccess';
                    $url = $service_content->href;
                    echo '<div class="delimiter"></div>';
                    echo '<a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a><br/>';
                    break;
                case 'loan':
                case 'presentation':
                    echo '<div class="delimiter"></div>';
                    if(!empty($item->storage->id)){
                        $level = 'link_external';
                        $label = $item->storage->content;
                        $url = $item->storage->id;
                        echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$url.'" class="'.$level.'" title="'.$label.'" target="_blank">'.$this->translate($label).'</a></span>';
                    } else {
                        echo $this->translate('unknown_location');
                    }
                    if(!empty($item->label)) echo ' <span class="item_label">'.$item->label.'</span>';
                    echo '<br>';
                    if(!empty($service_content->limitation[0]->id)) {
                        $limitation = substr($service_content->limitation[0]->id, strpos($service_content->limitation[0]->id, "#") + 1);
                        $level = $limitation;
                        $label = $service_content->service.$limitation;
                    } elseif(!empty($service_content->limitation[0]->content)) {
                        $limitation = $service_content->limitation[0]->content;
                        $level = $limitation;
                        $label = $service_content->service.$limitation;
                    } elseif(!empty($service_content->expected)) {
                        $level = "daia_orange";
                        $date = date_create($service_content->expected);
                        $label = $this->translate('on_loan_until').' '.date_format($date,"d.m.Y");
                    } else {
                        $level = "daia_green";
                        $label = $service_content->service;
                    }
                    echo '<span class="daia_hint"><span class="'.$level.'">'.$this->translate($label).'</span></span>';
                    echo '<span class="daia_arrow"> ➝ </span>';
                    if(!empty($service_content->href)) {
                        $url = $service_content->href;
                        $level = 'internal_link';
                        $url_components = parse_url($url);
                        parse_str($url_components['query'], $params);
                        $label = $params['action'];
                        echo '<span class="daia_action"><a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a></span>';
                    } else {
                        echo '<span class="daia_action">'.$this->translate($service_content->service.'_default_action'.$limitation).'</span>';
                    }
                    if(isset($service_content->queue)) {
                        $label = 'Recalls';
                        if($service_content->queue == 1) $label = 'Recall';
                        echo '<div class="service_queue">'.$service_content->queue.' '.$this->translate($label).'</div>';
                    }
                    if(!empty($item->about)) {
                        echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.$item->about.'</div>';
                    }
                    break;
                case 'fallback':
                    echo '<div class="delimiter"></div>';
                    if(!empty($item->storage->id)){
                        $level = 'link_external';
                        $label = $item->storage->content;
                        $url = $item->storage->id;
                        echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$url.'" class="'.$level.'" title="'.$label.'" target="_blank">'.$this->translate($label).'</a></span>';
                    } else {
                        echo $this->translate('unknown_location');
                    }
                    if(!empty($item->label)) echo ' <span class="item_label">'.$item->label.'</span>';
                    echo '<br>';
                    echo '<span class="daia_hint"><span class="daia_red">'.$this->translate('not_available').'</span></span>';
                    if(!empty($item->about)) {
                        echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.$item->about.'</div>';
                    }
                    break;
            }

            break;
        }
    }
    if($break == true) break;
}

foreach($resolver_data as $result) {
    echo '<div class="delimiter"></div>';
    if(!empty($result['storage'])) {
        echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$result['storage']['url'].'" class="'.$result['storage']['level'].'" title="'.$result['storage']['label'].'" target="_blank">'.$this->translate($result['storage']['label']).'</a></span>';
    }
    if($mode == 'break_on_first') break;
}

?>