<?php
    $url = '';
    $subito_base_url = 'https://www.subito-doc.de/preorder?';
    if($SB) {
        $url= $subito_base_url.'SB='.$SB.'&ND='.$ND;
    } else if ($SS) {
        $url= $subito_base_url.'ATI='.$ATI.'&JT='.$JT.'&SS='.$SS.'&VOL='.$VOL.'&APY='.$APY.'&PG='.$PG.'&CAT=ZDB';
    }
    if($url) {
        if(!$list) echo '<div class="availability_item">';
		echo '<div class="delimiter"></div>';
		echo '<a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a><br/>';
        if(!$list) echo '</div>';
	} 
?>