<?php
    $groups = [];
    $index = 0;
    $ppn = substr($data['document'][0]['id'], strrpos($data['document'][0]['id'], ':') + 1);
?>
<?php if ($this->source == 'Search2'): ?>
    <?php $recordRoute = 'Search2Record'; ?>
<?php else: ?>
    <?php $recordRoute = 'Record'; ?>
<?php endif; ?>
<?php $group_by_label = 'availabilityplus_daia_service'; ?>

<?php foreach ($data['document'][0]['item'] as $result): ?>
    <?php if (!empty($result['availabilityplus']['service'])): ?>
        <?php $groups[$result['availabilityplus']['service']][] = $result['availabilityplus']; ?>
        <?php if (empty($groups[$result['availabilityplus']['service']]['score'])): ?>
            <?php $groups[$result['availabilityplus']['service']]['score'] = $result['availabilityplus']['score']; ?>
        <?php else: ?>
            <?php if ($groups[$result['availabilityplus']['service']]['score'] > $result['availabilityplus']['score']): ?>
                <?php $groups[$result['availabilityplus']['service']]['score'] = $result['availabilityplus']['score']; ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php elseif (!empty($result['availabilityplus'])): ?>
        <?php $groups['undefined'][] = $result['availabilityplus']; ?>
        <?php if (empty($groups['undefined']['score'])): ?>
            <?php $groups['undefined']['score'] = $result['availabilityplus']['score']; ?>
        <?php else: ?>
            <?php if ($groups['undefined']['score'] > $result['availabilityplus']['score']): ?>
                <?php $groups['undefined']['score'] = $result['availabilityplus']['score']; ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($resolverConfig['sort_groups_by_score']): ?>
    <?php
        uasort($groups, function($a, $b) {
            return $a['score'] <=> $b['score'];
        });
    ?>
<?php endif; ?>

<?php $break = false; ?>
<?php foreach ($groups as $group_label => $group_items): ?>
    <?php
        unset($group_items['score']);
        $overlay = false;
        $overlay_label = 'no_overlay';
    ?>
    <?php if ($resolverConfig['overlay'] && $group_label !== 'undefined' && (sizeof($group_items) >= $resolverConfig['overlay_min_count'] || (!$list && $resolverConfig['always_display_overlay_in_record_view']))): ?>
        <?php
            $overlay = true;
            $overlay_label = 'overlay_used';
        ?>
    <?php endif; ?>

    <?php if ($overlay): ?>
        <div class="daiaplus-title <?=$group_by_label?>">
        <div class="group_label <?=$overlay_label?> <?=$group_label?> <?=$group_items[0]['daia_hint']['level']?>">
            <?=$this->transEsc("AvailabilityPlus::{$group_label}")?>
        </div>

        <?php if (!empty($group_items[0]['storage'])): ?>
            <?php if (!empty($group_items[0]['storage']['url'])): ?>
                <span class="storage_link">
                    <span class="storage_prefix"><?=$this->transEsc('AvailabilityPlus::department')?> </span>
                    <a href="<?=$group_items[0]['storage']['url']?>" class="<?=$group_items[0]['storage']['level']?>" title='<?=$this->transEsc("AvailabilityPlus::{$group_items[0]['storage']['label']}")?>' target="_blank">
                        <?=$this->transEsc("AvailabilityPlus::{$group_items[0]['storage']['label']}")?>
                    </a>
                </span>
            <?php else: ?>
                <span class="storage_link">
                    <span class="storage_prefix"><?=$this->transEsc('AvailabilityPlus::department')?></span>
                    <?=$this->transEsc("AvailabilityPlus::{$group_items[0]['storage']['label']}")?>
                </span>
            <?php endif; ?>
        <?php endif; ?>

        <?php $signature = ''; ?>
        <?php if (!empty($group_items[0]['epn'])): ?>
            <?php $item_epn = $group_items[0]['epn']; ?>
            <?php foreach ($SolrMarcSupportData as $key => $value): ?>
                <?php if (!empty($value['epn']['data'][0]) && $item_epn == $value['epn']['data'][0] && !empty($value['signature']['data'][0])): ?>
                    <?php
                        $signature = $value['signature']['data'][0];
                        break;
                    ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (empty($signature) && !empty($group_items[0]['callnumber'])): ?>
            <?php $signature = $group_items[0]['callnumber']; ?>
        <?php endif; ?>
        <?php if (!empty($signature)): ?>
            <span class="item_label"><?=$signature?></span>
        <?php endif; ?>

        <?php if (!empty($group_items[0]['chronology'])): ?>
            <div class="item_chronology">
                <span class="item_chronology_prefix"><?=$this->transEsc('AvailabilityPlus::Inventory Information')?>: </span>
                <?=$group_items[0]['chronology']?>
            </div>
        <?php endif; ?>

        <?php if ($list): ?>
            <div class="additional_copies">
                <a href="<?=$this->url('home')?><?=$recordRoute?>/<?=$id?>"><?=$this->transEsc('AvailabilityPlus::additional_copies')?>...</a>
            </div>
        <?php else: ?>
            <div>
                <a href="" class="daiaplus-overlay" data-daiaplus-overlay="daiaplus-overlay-<?=$ppn?>-<?=$index?>">
                    <?=$this->transEsc('AvailabilityPlus::show_overlay')?>
                </a>
            </div>
        <?php endif; ?>

        <div>
            <div id="daiaplus-overlay-<?=$ppn?>-<?=$index?>" style="display:none;">
    <?php else: ?>
        <?php if ($group_label !== 'undefined' && !in_array($group_label,array('openaccess','remote')) && !in_array($mode, ['break_on_first','break_on_first_next'])): ?>
            <div class="group_label <?=$overlay_label?> <?=$group_label?> <?=$group_items[0]['daia_hint']['level']?>">
                <?=$this->transEsc("AvailabilityPlus::{$group_label}")?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php foreach ($group_items as $key => $result): ?>
        <?php if (!empty($result)): ?>
            <div class="delimiter"></div>
            <?php if (!$list): ?>
                <div class="daia_item">
            <?php endif; ?>
        <?php endif; ?>
        <div class="daia_storage_callnumber">
            <?php if (!empty($result['storage'])): ?>
                <?php if (!empty($result['storage']['url'])): ?>
                    <span class="storage_link">
                        <span class="storage_prefix"><?=$this->transEsc('AvailabilityPlus::department')?> </span>
                        <a href="<?=$result['storage']['url']?>" class="<?=$result['storage']['level']?>" title='<?=$this->transEsc("AvailabilityPlus::{$result['storage']['label']}")?>' target="_blank">
                            1<?=$this->transEsc("AvailabilityPlus::{$result['storage']['label']}")?>
                        </a>
                    </span>
                <?php else: ?>
                    <span class="storage_link">
                        <span class="storage_prefix"><?=$this->transEsc('AvailabilityPlus::department')?></span>
                        <?=$this->transEsc("AvailabilityPlus::{$result['storage']['label']}")?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($result['callnumber'])): ?>
                <span class="item_label"><?=$result['callnumber']?></span>
            <?php endif; ?>
        </div>
        <?php if ($overlay && !empty($result['about'])): ?>
            <?php if ($mediatype == 'Journal'): ?>
                <div class="item_about"><span class="item_about_prefix"><?=$this->transEsc('AvailabilityPlus::volume_issue')?>: </span><?=str_replace("<br />",". - ", nl2br($result['about']))?></div>
            <?php else: ?>
                <div class="item_about"><span class="item_about_prefix"><?=$this->transEsc('AvailabilityPlus::item_about')?>: </span><?=str_replace("<br />",". - ", nl2br($result['about']))?></div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!empty($result['daia_hint'])): ?>
            <span class="daia_hint">
                <span class="<?=$result['daia_hint']['level']?>">
                    <?=$this->transEsc("AvailabilityPlus::{$result['daia_hint']['label']}");?>
                    <?php if (!empty($result['daia_hint']['label_date'])): ?>
                        <?=$result['daia_hint']['label_date']?>
                    <?php endif; ?>
                </span>
            </span>
        <?php endif; ?>
        <?php if (!empty($result['daia_hint']) && !empty($result['daia_action'])): ?>
            <span class="daia_arrow"> ➝ </span>
        <?php endif; ?>
        <?php if (!empty($result['daia_action'])): ?>
            <?php if (!empty($result['daia_action']['url'])): ?>
                <span class="daia_action">
                    <a href="<?=$result['daia_action']['url']?>" class="<?=$result['daia_action']['level']?> link_external" title='<?=$this->transEsc("AvailabilityPlus::{$result['daia_action']['label']}")?>' target="_blank">
                        <?=$this->transEsc("AvailabilityPlus::{$result['daia_action']['label']}")?>
                    </a>
                </span>
            <?php else: ?>
                <span class="daia_action"><?=$this->transEsc("AvailabilityPlus::{$result['daia_action']['label']}")?></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!$list): ?>
            <?php if (!empty($result['queue'])): ?>
                <div class="service_queue"><?=$result['queue']['length']?> <?=$this->transEsc("AvailabilityPlus::{$result['queue']['label']}")?></div>
            <?php endif; ?>
            <?php if (!empty($result['about'])): ?>
                <div class="item_about">
                    <span class="item_about_prefix"><?=$this->transEsc('AvailabilityPlus::item_about')?>: </span>
                    <?=str_replace('<br />', '. - ', nl2br($result['about']))?>
                </div>
            <?php endif; ?>
            <?php if (!empty($result['chronology'])): ?>
                <div class="item_chronology">
                    <span class="item_chronology_prefix"><?=$this->transEsc('AvailabilityPlus::Inventory Information')?>: </span>
                    <?=$result['chronology']?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!empty($result['order_hint'])): ?>
            <div class="order_hint"><?=$this->transEsc("AvailabilityPlus::{$result['order_hint']}")?></div>
        <?php endif; ?>
        <?php if (!empty($result)): ?>
            <?php if ($list && count($data['document'][0]['item']) > 1 && !empty($result['storage'])): ?>
                <div class="additional_copies">
                    <a href="<?=$this->url('home')?><?=$recordRoute?>/<?=$id?>"><?=$this->transEsc('AvailabilityPlus::additional_copies')?>...</a>
                </div>
            <?php endif; ?>
            <?php if (!$list): ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!$overlay && in_array($mode, ['break_on_first','break_on_first_next'])): ?>
            <?php
                $break = true;
                break;
            ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($overlay): ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if (in_array($mode, ['break_on_first','break_on_first_next'])): ?>
        <?php
            $break = true;
            break;
        ?>
    <?php endif; ?>
    <?php $index++; ?>
    <?php if ($break) break; ?>
<?php endforeach; ?>

<?php if (!empty($groups)): ?>
    <?php $script = <<<'JS'
        VuFind.itemStatuses.initDaiaPlusOverlay();
    JS;?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
<?php endif; ?>
