<?php

$storage_locations = [];
$index = 0;

foreach($data->document[0]->item as $result) {
    if(!empty($result->availabilityplus->storage)) {
        $storage_locations[$result->availabilityplus->storage->label][] = $result->availabilityplus;
        if(empty($storage_locations[$result->availabilityplus->storage->label]['score'])) {
            $storage_locations[$result->availabilityplus->storage->label]['score'] = $result->availabilityplus->score;
        } else {
            if($storage_locations[$result->availabilityplus->storage->label]['score'] > $result->availabilityplus->score) {
                $storage_locations[$result->availabilityplus->storage->label]['score'] = $result->availabilityplus->score;
            }
        }
    } else if(!empty($result->availabilityplus)) {
        $storage_locations['undefined'][] = $result->availabilityplus;
        if(empty($storage_locations['undefined']['score'])) {
            $storage_locations['undefined']['score'] = $result->availabilityplus->score;
        } else {
            if($storage_locations['undefined']['score'] > $result->availabilityplus->score) {
                $storage_locations['undefined']['score'] = $result->availabilityplus->score;
            }
        }
    }
}

uasort($storage_locations, function($a, $b) {
    return $a['score'] <=> $b['score'];
});

$break = false;
foreach($storage_locations as $storage_label => $storage_items) {

    $overlay = false;
    if ($storage_label !== 'undefined' && sizeof($storage_items) > 1) {
        $overlay = true;
    }

    if ($overlay) {
        echo '<div class="daiaplus-title">';
        if(!empty($storage_items[0]->storage->url)) {
            echo '<span class="storage_group"><a href="'.$storage_items[0]->storage->url.'" class="link_external" title="'.$storage_label.'" target="_blank">'.$this->translate($storage_label).'</a></span><br/>';
        } else {
            echo '<span class="storage_group">'.$this->translate($storage_label).'</span><br/>';
        }
        if(!empty($storage_items[0]->callnumber)) {
            echo ' <span class="item_label">' . $storage_items[0]->callnumber . '</span>';
        }
        if(!empty($result->chronology)) {
            echo '<div class="item_chronology"><span class="item_chronology_prefix">'.$this->translate('Inventory Information').': </span>'.$storage_items[0]->chronology.'</div>';
        }
        echo '<a href="" class="daiaplus-overlay" data-daiaplus-overlay="daiaplus-overlay-'.$index.'">'.$this->transEsc('show_overlay').'</a>';
        echo '<div>';
        echo '<div id="daiaplus-overlay-'.$index.'" style="display:none;">';
    } else {
        if($storage_label !== 'undefined') {
            echo '<div class="storage_group">'.$this->translate($storage_label).'</div>';
        }
    }

    foreach($storage_items as $key => $result) {
        if(!empty($result)) {
            echo '<div class="delimiter"></div>';
            if(!$list) echo '<div class="daia_item">';
        }
        echo '<div class="daia_storage_callnumber">';
        if(!empty($result->callnumber)) {
            echo ' <span class="item_label">' . $result->callnumber . '</span>';
        }
        echo '</div>';
        if(!empty($result->daia_hint)) {
            echo '<span class="daia_hint"><span class="'.$result->daia_hint->level.'">'.$this->translate($result->daia_hint->label);
            if(!empty($result->daia_hint->label_date)) echo ' '.$result->daia_hint->label_date;
            echo '</span></span>';
        }
        if(!empty($result->daia_hint) && !empty($result->daia_action)) {
            echo '<span class="daia_arrow"> ➝ </span>';
        }
        if(!empty($result->daia_action)) {
            if(!empty($result->daia_action->url)) {
                echo '<span class="daia_action"><a href="'.$result->daia_action->url.'" class="'.$result->daia_action->level.' link_external" title="'.$result->daia_action->label.'" target="_blank">'.$this->translate($result->daia_action->label).'</a></span>';
            } else {
                echo '<span class="daia_action">'.$this->translate($result->daia_action->label).'</span>';
            }
        }
        if(!$list){
            if(!empty($result->queue)) {
                echo '<div class="service_queue">'.$result->queue->length.' '.$this->translate($result->queue->label).'</div>';
            }
            if(!empty($result->about)) {
                echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.$result->about.'</div>';
            }
            if(!$overlay && !empty($result->chronology)) {
                echo '<div class="item_chronology"><span class="item_chronology_prefix">'.$this->translate('Inventory Information').': </span>'.$result->chronology.'</div>';
            }
        }
        if(!empty($result)) {
            if($list && count($data->document[0]->item) > 1 && !empty($result->storage)) {

                if($this->source == 'Search2') {
                    $recordRoute = 'Search2Record';
                } else {
                    $recordRoute = 'Record';
                }

                echo '<div class="additional_copies"><a href="/vufind/'.$recordRoute.'/'.$id.'">'.$this->transEsc('additional_copies').'...</a></div>';
            }
            if(!$list) echo '</div>';
        }
        if(in_array($mode, ['break_on_first','break_on_first_next'])) {
            $break = true;
            break;
        }
    }
    if($overlay) {
        echo '</div>';
        echo '</div>';
        echo '</div>';
    }
    $index++;
    if($break) break;
}
echo '<script type="text/javascript">initDaiaPlusOverlay()</script>';
?>