<?php if (!empty($data)): ?>
    <div class="fulltextfinder-result">
        <ul>
            <?php foreach ($data as $link): ?>
                <li>
                    <a href="<?=$link->targetUrl?>" title='<?=$this->transEsc("AvailabilityPlus::{$link->linkText}")?>' target="_blank">
                        <?=$this->transEsc("AvailabilityPlus::{$link->category}")?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
