<?php

$items = $data->document[0] ?? (object) array('item' => []);

if(in_array($mode, array('break_on_first', 'break_on_first_next', 'always_break_on_first')) && isset($data->best_item)) {
    unset($items);
    $items = (object) array('item' => array($data->best_item));
}

foreach($items->item as $key => $item) {
    if(isset($item->availabilityplus) && !empty($item->availabilityplus)) {
        $result = $item->availabilityplus;
    } else {
        break;
    }

    if(!empty($result)) {
        if(!isset($list) || !$list) echo '<div class="daia_item">';
        echo '<div class="delimiter"></div>';
    }
    echo '<div class="daia_storage_callnumber">';
    if(isset($result->storage) && !empty($result->storage) && isset($result->storage->label) && !empty($result->storage->label)) {
        if(isset($result->storage->url) && !empty($result->storage->url)) {
            echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$result->storage->url.'" class="'.($result->storage->level ?? '').'" title="'.$this->translate($result->storage->label).'" target="_blank">'.$this->translate($result->storage->label).'</a></span>';
        } else {
            echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').'</span> '.$this->translate($result->storage->label).'</span>';
        }

    }
        echo ' <span class="item_label">' . $result->callnumber . '</span>';
    if(isset($result->callnumber) && !empty($result->callnumber)) {
    }
    echo '</div>';
    if(isset($result->daia_hint) && !empty($result->daia_hint)) {
        echo '<span class="daia_hint"><span class="'.($result->daia_hint->level ?? '').'">'.$this->translate($result->daia_hint->label ?? '');
        if(isset($result->daia_hint->label_date) && !empty($result->daia_hint->label_date)) echo ' '.$result->daia_hint->label_date;
        echo '</span></span>';
    }
    if(isset($result->daia_hint) && !empty($result->daia_hint) && isset($result->daia_action) && !empty($result->daia_action)) {
        echo '<span class="daia_arrow"> ➝ </span>';
    }
    if(isset($result->daia_action) && !empty($result->daia_action) && isset($result->daia_action->label) && !empty($result->daia_action->label)) {
        if(isset($result->daia_action->url) && !empty($result->daia_action->url)) {
            echo '<span class="daia_action"><a href="'.$result->daia_action->url.'" class="'.($result->daia_action->level ?? '').' link_external" title="'.$result->daia_action->label.'" target="_blank">'.$this->translate($result->daia_action->label).'</a></span>';
        } else {
            echo '<span class="daia_action">'.$this->translate($result->daia_action->label).'</span>';
        }
    }
    if(!isset($list) || !$list){
        if(isset($result->queue) && !empty($result->queue)) {
            echo '<div class="service_queue">'.($result->queue->length ?? '0').' '.$this->translate($result->queue->label ?? '').'</div>';
        }
        if(isset($result->about) && !empty($result->about)) {
            if($mediatype == 'Journal') {
                echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('volume_issue').': </span>'.str_replace("<br />",". – ", nl2br($result->about)).'</div>';
            } else {
                echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.str_replace("<br />",". – ", nl2br($result->about)).'</div>';
            }
        }
        if(isset($result->chronology) && !empty($result->chronology)) {
            echo '<div class="item_chronology"><span class="item_chronology_prefix">'.$this->translate('Inventory Information').': </span>'.$result->chronology.'</div>';
        }
    }
    if (isset($result->order_hint) && !empty($result->order_hint)) echo '<div class="order_hint">'.$this->translate($result->order_hint).'</div>';
    if(!empty($result)) {
        if(isset($list) && !empty($list) && isset($result->storage) && !empty($result->storage)) {

            if($this->source == 'Search2') {
                $recordRoute = 'Search2Record';
            } else {
                $recordRoute = 'Record';
            }

            echo '<div class="additional_copies"><a href="/vufind/'.$recordRoute.'/'.$id.'">'.$this->transEsc('additional_copies').'...</a></div>';
        }
        if(!isset($list) || !$list) echo '</div>';
    }
    if($mode == 'break_on_first') break;
}

?>
