<?php
foreach($data as $result) {
   if(isset($result['label']) && !empty($result['label'])){
      if(!isset($list) || !$list) echo '<div class="availability_item">';
      $level = $result['level'] ?? '';
      $label = $result['label'] ?? '';
      $url = $result['url'] ?? '#';
      echo '<div class="delimiter"></div>';
      echo '<a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a><br/>';
      if(!isset($list) || !$list) echo '</div>';
      if($mode == 'break_on_first') break;
   }
}
?>
