<?php

if($mode == 'break_on_first' && $data->best_item) {
    $data_temp[0] = $data->best_item;
    $data = $data_temp[0];
}

foreach($data as $result) {
    if(!empty($result['label'])){
        if(!$list) echo '<div class="availability_item">';
        $level = $result['level'];
        $label = $result['label'];
        $url = $result['url'];
        echo '<div class="delimiter"></div>';
        echo '<a href="'.$url.'" class="'.$level.' link_external" title="'.$label.'" target="_blank">'.$this->translate($label).'</a><br/>';
        if(!$list) echo '</div>';
        if($mode == 'break_on_first') break;
    }
}
?>
