<div class="is-content-area">
	<h1><?=$this->transEsc('Contact')?></h1>

    <p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.</p>
    <p><strong>Organisation</strong><br/>Prof. Dr. Silke Musterfrau<br/>Mustercampus 500<br/>12345 Musterstadt<br/><a href="mailto:#">E-Mail schreiben</a></p>

</div>