<? $coreFields = $this->solrDefault()->getCoreFields($this->driver, $this->coreFieldCategory); ?>
<? if (!empty($coreFields)): ?>
      <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
        <? foreach ($coreFields as $field => $items): ?>
            <? if (!empty($items[0])): ?>
          <tr><th><?=$this->transEsc($field)?>:</th><td>
            <? foreach ($items as $item): ?>
             <p>
                <? foreach ($item as $key => $value): ?>
                   <? if (!is_int($key)): ?>
                      <?=$this->transEsc($key) ?>:
                   <? endif; ?>
                   <?=$value ?><br />
                <? endforeach; ?>
             </p>
           <? endforeach; ?>
          </td></tr>
           <? endif; ?>
        <? endforeach; ?>
      </table>
    <? endif; ?>
