<?php
if (empty($this->coreFieldCategories)):
    $coreFieldList = [$this->solrDetails()->getCoreFields($this->driver, [])];
else:
    $coreFieldList = [];
    foreach ($this->coreFieldCategories as $category):
        $coreFieldList[] = $this->solrDetails()->getCoreFields($this->driver, [$category]);
    endforeach;
endif;
?>
<?php //print_r($coreFieldList); ?>
<?php foreach ($coreFieldList as $coreFields): ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
        <?php foreach ($coreFields as $field => $items): ?>
            <?php if (!empty($items[0])): ?>
          <tr><th><?=$this->transEsc($field)?>:</th><td>
                <?php foreach ($items as $item): ?>
             <p style="margin:0px">
                 <?php if (false): ?>
                        <?php if (!empty($value['originalLetters']) && $value['originalLetters'] != $value['data']): ?>
                            <?=$this->transEsc('Original Letters') ?>: <?=$value['originalLetters'] ?><br />
                         <?php endif; ?>
                 <?php else: ?>
                    <?=$item ?>
                 <?php endif; ?>
             </p>
                <?php endforeach; ?>
          </td></tr>
             <?php endif; ?>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
<?php endforeach; ?>
