<?
$coverDetails = $this->record($this->driver)->getCoverDetails('result-list', 'medium', $this->recordLinker()->getUrl($this->driver));
$cover = $coverDetails['html'];
$thumbnail = false;
$thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?> belugax-cover">
        <?=$cover ?>
    </div>
    <? $thumbnail = ob_get_contents(); ?>
    <? ob_end_clean(); ?>
<? endif; ?>
<input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>" class="hiddenId" />
<input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource" />
<div class="media">
    <div class="media-left medium belugax-cover">
        <? foreach ($this->driver->getFormats() as $format): ?>
            <? if ($belugino = $this->configreader()->getConfigData('belugino', $format)): ?>
                <i class="<?=$belugino?> belugino-icon-cover" aria-hidden="true" title="<?=$this->transEsc($format) ?>"></i>
            <? else: ?>
                <i class="bel-unbek belugino-icon-cover" aria-hidden="true" title="<?=$this->transEsc($format) ?>"></i>
            <? endif; ?>
        <? endforeach; ?>
    </div>
    <div class="media-body">
        <div class="result-body result-body-cart">
            <div class="result-body-details">
                <!-- Module RecordDriver -->
                <?=$this->render('RecordDriver/SolrDefault/recorddriver-result-list.phtml', ['params' => null, 'driver' => $this->driver]) ?>
                <!-- Module RecordDriver -->
            </div>

            <? if(!$this->driver->isCollection()): ?>
                <? if ($snippet = $this->driver->getHighlightedSnippet()): ?>
                    <? if (!empty($snippet['caption'])): ?>
                        <strong><?=$this->transEsc($snippet['caption']) ?>:</strong> ';
                    <? endif; ?>
                    <? if (!empty($snippet['snippet'])): ?>
                        <span class="quotestart">&#8220;</span>...<?=$this->highlight($snippet['snippet']) ?>...<span class="quoteend">&#8221;</span><br/>
                    <? endif; ?>
                <? endif; ?>
            <? endif; ?>

            <?
            /* Display information on duplicate records if available */
            if ($dedupData = $this->driver->getDedupData()): ?>
                <div class="dedupInformation">
                    <?
                    $i = 0;
                    foreach ($dedupData as $source => $current) {
                    if (++$i == 1) {
                        ?><span class="currentSource"><a href="<?=$this->recordLinker()->getUrl($this->driver)?>" data-lightbox-ignore><?=$this->transEsc("source_$source", [], $source)?></a></span><?
                    } else {
                    if ($i == 2) {
                    ?> <span class="otherSources">(<?=$this->transEsc('Other Sources')?>: <?
                        } else {
                            ?>, <?
                        }
                        ?><a href="<?=$this->recordLinker()->getUrl($current['id'])?>" data-lightbox-ignore><?=$this->transEsc("source_$source", [], $source)?></a><?
                        }
                        }
                        if ($i > 1) {
                        ?>)</span><?
                }?>
                </div>
            <? endif; ?>

            <div class="result-body-daia">
                <!--Module AvailabilityPlus-->
                <?=$this->render('RecordDriver/SolrDefault/availabilityplus-result-list.phtml', ['driver' => $this->driver]) ?>
                <!--Module AvailabilityPlus-->
            </div>

            <div class="result-previews">
                <?=$this->record($this->driver)->getPreviews()?>
            </div>
        </div>
        <? /*
    <div class="result-links hidden-print">
      <? // Display qrcode if appropriate: ?>
      <? if ($QRCode = $this->record($this->driver)->getQRCode("results")): ?>
        <?
          // Add JS Variables for QrCode
          $this->jsTranslations()->addStrings(['qrcode_hide' => 'qrcode_hide', 'qrcode_show' => 'qrcode_show']);
        ?>
        <span class="hidden-xs">
          <i class="fa fa-fw fa-qrcode" aria-hidden="true"></i> <a href="<?=$this->escapeHtmlAttr($QRCode);?>" class="qrcodeLink" data-lightbox-ignore><?=$this->transEsc('qrcode_show')?></a>
          <div class="qrcode hidden">
            <script type="text/template" class="qrCodeImgTag">
              <img alt="<?=$this->transEsc('QR Code')?>" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
            </script>
          </div><br/>
        </span>
      <? endif; ?>

      <? // Hierarchy tree link ?>
      <? $trees = $this->driver->tryMethod('getHierarchyTrees'); if (!empty($trees)): ?>
        <? foreach ($trees as $hierarchyID => $hierarchyTitle): ?>
          <div class="hierarchyTreeLink">
            <input type="hidden" value="<?=$this->escapeHtmlAttr($hierarchyID)?>" class="hiddenHierarchyId" />
            <i class="result-link-icon bel-orgaform" aria-hidden="true"></i>
            <a class="hierarchyTreeLinkText result-link-label" data-lightbox href="<?=$this->recordLinker()->getTabUrl($this->driver, 'HierarchyTree')?>?hierarchy=<?=urlencode($hierarchyID)?>#tabnav" title="<?=$this->transEsc('hierarchy_tree')?>" data-lightbox-href="<?=$this->recordLinker()->getTabUrl($this->driver, 'AjaxTab')?>?hierarchy=<?=urlencode($hierarchyID)?>" data-lightbox-post="tab=hierarchytree">
              <?=$this->transEsc('hierarchy_view_context')?><? if (count($trees) > 1): ?>: <?=$this->escapeHtml($hierarchyTitle)?><? endif; ?>
            </a>
          </div>
        <? endforeach; ?>
      <? endif; ?>

      <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>':''?>
    </div>
    */ ?>
    </div>
    <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
        <?=$thumbnail ?>
    <? endif ?>
</div>
