# Configuration of Test Cases to check
# Configured Test Cases can be viewed and checked here: /vufind/AvailabilityPlus/TestCases
# Format is:
# -------------
# <id>: # id of record in index
#  driver: '<driver to load record>' # required, Solr, Search2, ...
#  description: '<short description of test case>' # optional, text
#  expected: # definition of expected results, optional, array
#    description: '<description of what is expected to appear as availability>' # optional, text
#    description_xy: '<description of what is expected to appear as availability for specific language selected in VuFind, xy represents language code, supersedes expected->description>' # optional, text, multiple possible, up to one for every language code used in VuFind installation
#    html: '<html which is expected to appear as availability, supersedes expected->description_xy>' # optional, html
#    html_xy: '<html which is expected to appear as availability for specific language selected in VuFind, xy represents language code, supersedes expected->html>' # optional, html, multiple possible, up to one for every language code used in VuFind installation
#    resultlist: # expected availability for result list view, optional, array
#      description: '<description of what is expected to appear as availability in listview, supersedes any node with text or html directly below expected>' # optional, text
#      description_xy: '<description of what is expected to appear as availability in listview for specific language selected in VuFind, xy represents language code, supersedes expected->listview->description>' # optional, text, multiple possible, up to one for every language code used in VuFind installation
#      html: '<html which is expected to appear as availability in listview, supersedes expected->listview->description_xy>' # optional, html
#      html_xy: '<html which is expected to appear as availability in listview for specific language selected in VuFind, xy represents language code, supersedes expected->öistview->html>' # optional, html, multiple possible, up to one for every language code used in VuFind installation
#    recordview: # expected availability for record view, optional, array
#      description: '<description of what is expected to appear as availability in recordview, supersedes any node with text or html directly below expected>' # optional, text
#      description_xy: '<description of what is expected to appear as availability in recordview for specific language selected in VuFind, xy represents language code, supersedes expected->recordview->description>' # optional, text, multiple possible, up to one for every language code used in VuFind installation
#      html: '<html which is expected to appear as availability in recordview, supersedes expected->recordview->description_xy>' # optional, html
#      html_xy: '<html which is expected to appear as availability in recordview for specific language selected in VuFind, xy represents language code, supersedes expected->öistview->html>' # optional, html, multiple possible, up to one for every language code used in VuFind installation
#  title: '<title of publication as reference>' # optional, text
#  reason: '<reason for adding test case>' # optional, text
#  date: '<date when test case was added>' # optional, date yyyy-mm-dd
#  creator: '<name of person who added or suggested test case>' # optional, text
#  rules: 'use to mention rule from availabilityplus-resolver-<driver>.yaml if tested by test case' # optional, text
#  detailsLink: '<url which leads to more details about this test case, e.g. a GitHub Issue, an internal GitLab Issue>' # optional, url
# -------------
# Example:
# -------------
# 123456789:
#  driver: 'Solr'
#  description: 'sample description'
#  expected:
#    resultlist:
#      html_en: '<a href="https://www.fulltext.com">Fulltext</a>'
#      html_de: '<a href="https://www.fulltext.com">Volltext</a>'
#    recordview:
#      description_en: 'access information'
#      description_de: 'Zugangsinformation'
#  title: 'Example Title'
#  reason: 'to give an example for test cases'
#  date: '2022-04-09'
#  creator: 'Jon Doe'
#  rules: 'no rule applicable'
#  detailsLink: 'http://www.test.com'
1019193735:
  driver: 'Solr'
  description: '1 Zugang Verfügbarkeit - ausleihbares Exemplar (Stand 21.04.2020)'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
1011145693:
  driver: 'Solr'
  description: '2 Zugang Verfügbarkeit - entliehenes Exemplar (Stand 21.04.2020)'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
125181450:
  driver: 'Solr'
  description: '3 Zugang Verfügbarkeit - Präsenzexemplar'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
102330063X:
  driver: 'Solr'
  description: '4 Zugang Verfügbarkeit - Mehrfachexemplare'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
1665419822:
  driver: 'Solr'
  description: '5 Zugang Verfügbarkeit - Sonderstandort Dienstapparate'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
129305618:
  driver: 'Solr'
  description: '7 Zugang Verfügbarkeit - Zeitschrift mit Vorhandenen Bänden, Bestandsinformationen'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
858909626:
  driver: 'Solr'
  description: '8 Zugang Verfügbarkeit - E-Zeitschrift'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
725791020:
  driver: 'Solr'
  description: '9 Zugang Verfügbarkeit - Bandinformationen aus dem OUS'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
1666800538:
  driver: 'Solr'
  description: '12 Zugang Verfügbarkeit - Mehrbändiges Werk mit vorhandenen Bänden'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
777511673:
  driver: 'Solr'
  description: '13 Zugang Verfügbarkeit - E-Book-Hinweise'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
#1645516261:
#  driver: 'Solr'
#  description: '22 Suchraumerweiterung - Hamburger Bibliotheken - Namen und Verlinkungen zu Katalogen'
#  expected:
#    description: ''
#    html: ''
#  reason: ''
#  date: ''
#  creator: ''
#  rules: ''
#  detailsLink: ''
1032306637:
  driver: 'Solr'
  description: '21 Suchraumerweiterung - Verbundkatalog - Fernleihlinks'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
540325791:
  driver: 'Solr'
  description: 'Buch Verlust'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
824845498:
  driver: 'Solr'
  description: 'Monographische Reihe'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
168748306X:
  driver: 'Solr'
  description: 'Übergeordnetes Werk'
  expected:
    description: ''
    html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: ''
167052650X:
  driver: 'Search2'
  description: 'Übergeordnetes Werk aus MARC-Daten'
  expected:
    description: 'Link zu übergeordnetem Werk vorhanden'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/hcu/-/issues/142#note_18715'
1636097154:
  driver: 'Search2'
  description: 'Übergeordnetes Werk aus MARC-Daten'
  expected:
    description: 'Link zu übergeordnetem Werk vorhanden'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/hcu/-/issues/142#note_18715'
612132862:
  driver: 'Search2'
  description: 'Print-Bestand aus JOP erkannt'
  expected:
    description: 'Gedruckt vorhanden: [Signatur] (mit oder ohne Verlinkung zur Signatursuche?'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/hcu/-/issues/142#note_18715'

1775924033:
  driver: 'Solr'
  description: 'Titel im Erwerbungsvorgang'
  expected:
    description: 'Titel ist<br>bestellt'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
1757294570:
  driver: 'Solr'
  description: 'Weiterer Sonderstandort Semesterapparate'
  expected:
    description: 'Erdgeschoss, Semesterapparat Fusi 1 ZH 3450 006 (43) Nur in der Bibliothek nutzbar'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
1698030681:
  driver: 'Solr'
  description: 'Hamburger Suchraumerweiterung (taucht in Ergebnisliste gar nicht auf)'
  expected:
    description: 'Ergebnisliste: Entfernen der Verlinkung zum GVK bei Suchraumerweiterung zu Hamburger Bibliotheken / Detailanzeige: Link zur Fernleihe'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
179075527:
  driver: 'Solr'
  description: 'Buch Vermisst'
  expected:
    description: '2. Obergeschoss Hs 32 Derzeit nicht vorhanden. Bitte an der Servicetheke melden. Currently not available. Please refer to the service desk.'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
83740083X:
  driver: 'Solr'
  description: 'Monographische Reihe'
  expected:
    description: 'Ergebnisliste: Link "vorhandene Bände" / Detailanzeige: siehe vorhandene Bände unten'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
520199642:
  driver: 'Solr'
  description: 'Suchraumerweiterung GVK: Zeitschrift mit Bandaufnahmen'
  expected:
    description: 'Bibliothek / Fernleihe prüfen; Bei Klick auf Band in Detailanzeige Weitersuche nach Band in GVK zwecks Ermittlung der besitzenden Bibliothek oder Absetzen einer Fernleihbestellung'
  html: ''
  reason: ''
  date: ''
  creator: ''
  rules: ''
  detailsLink: 'https://gitlab.effective-webwork.de/beluga/availabilityplus/-/issues/91#note_20175'
