<div id="DependentWorks" style="display:none">
    <h4><?=$this->transEsc('DependentWorks') ?></h4>
    <ul id="DependentWorks" style="margin-bottom:0px;"></ul>
    <p id="ToggleDependentWorksMore" style="display:none">
        <a href=""><?=$this->transEsc('more') ?></a>
    </p>
    <ul id="DependentWorksHidden" style="margin-top:0px;display:none"></ul>
    <p id="ToggleDependentWorksLess" style="display:none">
        <a href=""><?=$this->transEsc('less') ?></a>
    </p>
</div>