<div id="belugax-staff-view">
    <div id="belugax-staff-view-title" class="uk-align-right">
        <a uk-toggle="target: .belugax-staff-view-toggle" type="button">
            <?=$this->translate('Staff View')?>
            <i class="bel-pfeil-u01 belugax-staff-view-toggle" aria-hidden="true"></i>
            <i class="bel-pfeil-o01 belugax-staff-view-toggle" aria-hidden="true" hidden></i>
        </a>
    </div>
    <div id="belugax-staff-view-content" class="belugax-staff-view-toggle" hidden>
        <?=\VuFind\XSLT\Processor::process('record-marc.xsl', $xml)?>
    </div>
</div>
