<?
//$language = $this->layout()->userLang;
//$ppn = $_GET['ppn'];
//$list = $_GET['list'];
//$mediatype = $_GET['mediatype'];
//$marcField951aValue = urldecode($_GET['marcField951aValue']);

echo '<div id="paia-availability">';
if ($list) {
    if(isset($daiaResults_org['daiaplus_best_result'])) {
        echo '<div class="delimiter"></div>';
    }
    $daiaResults[] = $daiaResults_org['daiaplus_best_result'];
} else {
    if(isset($daiaResults_org['daiaplus_best_result'])) {
        unset($daiaResults_org['daiaplus_best_result']);
    }

    if(!empty($daiaResults_org)) {
        $useDaia = true;
        $daiaResults = $daiaResults_org;
    } else {
        $useDaia = false;
    }

    echo '<div id="daia_results">';
    echo '<a name="availability"></a>';
    echo'<table>';
    echo'<tbody>';
    if(!$useDaia) {
        echo'<tr>';
        echo'<td valign="top">';
        echo $this->transEsc('please select a volume');
        echo'</td>';
        echo'</tr>';
    }

}

foreach ($daiaResults as $daiaResult) {

echo'<table>';
    if(!$list) {
        echo'<tr>';
        echo'<td valign="top">';
    }

    $storage = $daiaResult['daiaplus']['storage'];
    if($storage['id']) {
        $storage = '<a href="'.$storage['id'].'" target="_blank">'.$storage['content'].'</a>';
    } else {
        $storage = $storage['content'];
    }
    $storage_additional_info = $daiaResult['daiaplus']['storage_additional_info_custom'];
    if (empty($storage_additional_info)) {
        $storage_additional_info = $daiaResult['daiaplus']['storage_additional_info'];
    }

    $about = $daiaResult['daiaplus']['about'];
    $label = $daiaResult['daiaplus']['label'];

    if ($marcField951aValue == 'AI') {
        $label = $this->transEsc("Containing Work").": ".$label;
    }
    if(empty($daiaResult['daiaplus']['action']) || in_array($daiaResult['daiaplus']['action']['service'],array("loan","presentation"))) {
        if (($daiaResult['daiaplus']['department'] != '' || $daiaResult['daiaplus']['storage'] != '' || $daiaResult['daiaplus']['label'] != '')) {
            if ($daiaResult['daiaplus']['showDepartment']) {
                echo $this->transEsc('department').': '.$daiaResult['daiaplus']['department'].' - '.$storage.' <b>'.$label.'</b><br/>';
            } else {
                echo $this->transEsc('department').': '.$storage.' <b>'.$label.'</b><br/>';
            }
        }
    }

    $status = $daiaResult['daiaplus']['status'];
    //$action = $daiaResult['daiaplus']['action'];
    $actionArray = $daiaResult['daiaplus']['actionArray'];

    if($status != '' && (empty($daiaResult['daiaplus']['action']) || in_array($daiaResult['daiaplus']['action']['service'],array("loan","presentation")))) {
        echo '<span class="'.$daiaResult['daiaplus']['status_class'].'">'.$this->transEsc($status).'</span>';
    }

    /* if (!empty($action)) {
        if(!empty($action['generic'])) {
            $action_href = $action['generic']['href'];
            $action_label = $action['generic']['label'];
        } else if (!empty($action['beluga_core'])) {
            $action_href = $action['beluga_core']['href'];
            $action_label = $action['beluga_core']['label'];
        }

        if($action['link_status']) {
            $action_label .= ' '.$this->transEsc($action['link_status']);
        }

        if($status != '' && (empty($daiaResult['daiaplus']['action']) || in_array($daiaResult['daiaplus']['action']['service'],array("loan","presentation")))) {
            echo ' &#10141;';
        }
        echo ' <span class="daia_action">';
        if($action_href) {
            echo '<a class="'.$action['link_status'].'" href="'.$action_href.'" target="_blank">'.$action_label.'</a>';
        } else {
            echo $action_label;
        }
        echo '</span>';
    } */

    if (!empty($actionArray)) {
        foreach ($actionArray as $actionEntry) {
            if(!empty($actionEntry['generic'])) {
                $action_href = $actionEntry['generic']['href'];
                $action_label = $actionEntry['generic']['label'];
            } else if (!empty($actionEntry['beluga_core'])) {
                $action_href = $actionEntry['beluga_core']['href'];
                $action_label = $actionEntry['beluga_core']['label'];
            }

            if($actionEntry['link_status']) {
                $action_label .= ' '.$this->transEsc($actionEntry['link_status']);
            }

            if($status != '' && (empty($daiaResult['daiaplus']['action']) || in_array($daiaResult['daiaplus']['action']['service'],array("loan","presentation")))) {
                echo ' &#10141;';
            }
            echo ' <span class="daia_action">';
            if($action_href) {
                echo '<a class="'.$actionEntry['link_status'].'" href="'.$action_href.'" target="_blank">'.$action_label.'</a>';
            } else {
                echo $action_label;
            }
            echo '</span>';
        }
    }

    if($list) {
        if ($daiaResult['daiaplus']['list_more_link']) {
            echo '<br><a href="'.$this->recordLink()->getUrl($this->driver).$ppn.'#availability">'.$this->transEsc('additional_copies').'...</a>';
        }
    } else {
        if ($daiaResult['daiaplus']['queue'] != '') {
            echo'<br/>'.$daiaResult['daiaplus']['queue'];
        }

        if ($about != '') {
            if ($mediatype == "Journal" || $mediatype == "eJournal") {
                echo'<br/><strong>'.$this->transEsc('volume_issue').': '.$about.'</strong>';
            } else if ($mediatype == "Book") {
                echo'<br/><strong>'.$this->transEsc('Copy').': '.$about.'</strong>';
            } else {
                echo'<br/><strong>'.$about.'</strong>';
            }
        }

        if (!empty($storage_additional_info['content'])) {
            echo '<strong> / ';
            if (!empty($storage_additional_info['href'])) {
                echo '<a href="'.$storage_additional_info['href'].'" target="_blank">';
            }
            echo $storage_additional_info['content'];
            if (!empty($storage_additional_info['href'])) {
                echo '</a>';
            }
            echo '</strong>';
        }
        echo'</td>';
        echo'</tr>';
    }
}
echo'</table>';

 if (!$list) {
    echo'</tbody>';
    echo'</table>';
    echo'</div>';
}

/*
echo '<div style="display:none;"><pre>';
print_r($daiaResults_org);
echo '</pre></div>';
echo '<div style="display:none;"><pre>';
echo json_encode($daiaResults_org, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
echo '</pre></div>';
echo '</div>';
*/
