<script type="text/javascript">
function toggleDependentWorks() {
    var dependentWorksLayer = document.getElementById('DependentWorksHidden');
    var toggleMore = document.getElementById('ToggleDependentWorksMore');
    var toggleLess = document.getElementById('ToggleDependentWorksLess');
    if (dependentWorksLayer.style.display == 'none') {
        dependentWorksLayer.style.display = 'block';
        toggleMore.style.display = 'none';
        toggleLess.style.display = 'block';
    } else {
        dependentWorksLayer.style.display = 'none';
        toggleMore.style.display = 'block';
        toggleLess.style.display = 'none';
    }
}
</script>
<h4><?=$this->transEsc('Dependent Works') ?></h4>
<div id="DependentWorks" style="display:none">
<h4><?=$this->transEsc('Dependent Works') ?></h4>
<ul id="DependentWorks"></ul>
<p id="ToggleDependentWorksMore" style="display:none"><a href="javascript:toggleDependentWorks()"><?=$this->transEsc('more') ?></a></p>
<ul id="DependentWorksHidden" style="display:none"></ul>
<p id="ToggleDependentWorksLess" style="display:none"><a href="javascript:toggleDependentWorks()"><?=$this->transEsc('less') ?></a></p>
</div>

