<?
if (empty($this->coreFieldCategories)):
    $coreFieldList = [$this->solrDefault()->getCoreFields($this->driver, $this->coreFieldCategories)];
else:
    $coreFieldList = [];
    foreach ($this->coreFieldCategories as $category):
        $coreFieldList[] = $this->solrDefault()->getCoreFields($this->driver, [$category]);
    endforeach;
endif;
?>
<? foreach ($coreFieldList as $coreFields): ?>
    <? if (!empty($coreFields)): ?>
      <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
        <? foreach ($coreFields as $field => $items): ?>
            <? if (!empty($items[0])): ?>
          <tr><th><?=$this->transEsc($field)?>:</th><td>
                <? foreach ($items as $item): ?>
             <p style="margin:0px">
                 <? if (is_array($item)): ?>
                    <? foreach ($item as $key => $value): ?>
                        <? if (!is_int($key)): ?>
                            <?=$this->transEsc($key) ?>:
                        <? endif; ?>
                        <?=$value ?><br />
                    <? endforeach; ?>
                 <? endif; ?>
             </p>
                <? endforeach; ?>
          </td></tr>
             <? endif; ?>
        <? endforeach; ?>
      </table>
    <? endif; ?>
<? endforeach; ?>
