<? $titleFields = $this->solrDetails()->getCoreFields($this->driver, ['title']); ?>
<? if (!empty($titleFields['ShortTitle'][0][0])): ?>
    <h3 property="name">
        <?= (!empty($titleFields['ShortTitle'][0][0])) ? $this->transEsc($titleFields['ShortTitle'][0][0]) . ' ' : '' ?>
        <?= (!empty($titleFields['SubTitle'][0][0])) ? $this->transEsc($titleFields['SubTitle'][0][0]) . ' ' : '' ?>
        <?= (!empty($titleFields['TitleSection'][0][0])) ? '; ' . $this->transEsc($titleFields['TitleSection'][0][0]) . ' ' : '' ?>
        <?= (!empty($titleFields['TitleSection'][0]['description'])) ? $this->transEsc($titleFields['TitleSection'][0]['description']) . ' ' : '' ?>
        <?= (!empty($titleFields['TitleStatement'][0][0])) ? '/ ' . $this->transEsc($titleFields['TitleStatement'][0][0]) : '' ?>
    </h3>
<? endif; ?>
<? if (!empty($titleFields['Summary'][0][0])): ?>
    <? $summary = $titleFields['Summary'][0][0]; ?>
      <div id="belugax-summary">
        <span id="belugax-summary-preview"><?=$this->truncate($summary, 300)?></span>
        <span id="belugax-summary-full" class="hidden"><?=$summary?></span>
        <? if(strlen($summary) > 300): ?>
          <a id="belugax-summary-toggle"><i class="bel-pfeil-u01"></i></a>
        <? endif; ?>
      </div>
<? endif; ?>
