<?php foreach ($this->authenticator()->getDeliveryDomains() as $domain): ?>
    <?php if ($this->authenticator()->isAuthorized($domain)): ?>
        <?php $templateParams = $this->authenticator()->getTemplateParams($domain); ?>
        <?php if ($templateParams['show_home'] == 'y'): ?>
    <a href="<?=$this->url('delivery-home')?>" <?=$this->active == 'delivery' ? ' class="active"' : ''?>>
            <?php if (!empty($templateParams['icon'])): ?>
<img src="<?=$this->imageLink($templateParams['icon'])?>" style="height:12px;margin:0px 0px 0px 0px" aria-hidden="true">
            <?php elseif (!empty($templateParams['belugino'])): ?>
<i class="<?=$templateParams['belugino']?>" aria-hidden="true"></i>
            <?php endif; ?>
         <?=$this->transEsc($templateParams['title'])?>
    </a>
        <?php endif; ?>
    <?php endif; ?>
<?php endforeach; ?>
