<?php

if ($mediatype == 'Journal' && $list) {
    if($this->source == 'Search2') {
        $recordRoute = 'Search2Record';
    } else {
        $recordRoute = 'Record';
    }

    echo '<div class="JournalVolumes"><a href="/vufind/'.$recordRoute.'/'.$id.'">'.$this->transEsc('JournalVolumes').'</a></div>';
} else {
    $items = $data->document[0];

    if($mode == 'break_on_first' && $data->best_item) {
	$items = (object)'';
        $items->item[0] = $data->best_item;
    }

    foreach($items->item as $key => $item) {
        if(!empty($item->availabilityplus)) {
            $result = $item->availabilityplus;
        } else {
            break;
        }
        if(!empty($result)) {
            if(!$list) echo '<div class="daia_item">';
            echo '<div class="delimiter"></div>';
        }
        echo '<div class="daia_storage_callnumber">';
        if(!empty($result->storage)) {
            if(!empty($result->storage->url)) {
                echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').' </span><a href="'.$result->storage->url.'" class="'.$result->storage->level.'" title="'.$result->storage->label.'" target="_blank">'.$this->translate($result->storage->label).'</a></span>';
            } else {
                echo '<span class="storage_link"><span class="storage_prefix">'.$this->translate('department').'</span> '.$this->translate($result->storage->label).'</span>';
            }

        }
        if(!empty($result->callnumber)) {
            echo ' <span class="item_label">' . $this->translate($result->callnumber) . '</span>';
        }
        echo '</div>';
        if(!empty($result->daia_hint)) {
            echo '<span class="daia_hint"><span class="'.$result->daia_hint->level.'">'.$this->translate($result->daia_hint->label);
            if(!empty($result->daia_hint->label_date)) echo ' '.$result->daia_hint->label_date;
            echo '</span></span>';
        }
        if(!empty($result->daia_hint) && !empty($result->daia_action)) {
            echo '<span class="daia_arrow"> ➝ </span>';
        }
        if(!empty($result->daia_action)) {
            if(!empty($result->daia_action->url)) {
                echo '<span class="daia_action"><a href="'.$result->daia_action->url.'" class="'.$result->daia_action->level.' link_external" title="'.$result->daia_action->label.'" target="_blank">'.$this->translate($result->daia_action->label).'</a></span>';
            } else {
                echo '<span class="daia_action">'.$this->translate($result->daia_action->label).'</span>';
            }
        }
        if(!isset($list) || !$list){
            if(!empty($result->queue)) {
                echo '<div class="service_queue">'.$result->queue->length.' '.$this->translate($result->queue->label).'</div>';
            }
            if(!empty($result->about)) {
                echo '<div class="item_about"><span class="item_about_prefix">'.$this->translate('item_about').': </span>'.str_replace("<br />",". – ", nl2br($result->about)).'</div>';
            }
            if(!empty($result->chronology)) {
                echo '<div class="item_chronology">';
                if(stristr($result->chronology,'lizenziert') === FALSE) echo '<span class="item_chronology_prefix">'.$this->translate('Inventory Information').': </span>';
                echo $result->chronology.'</div>';
            }
        }
        if(!empty($result) && isset($list)) {
            if($list && count($data->document[0]->item) > 1 && !empty($result->storage)) {

                if($this->source == 'Search2') {
                    $recordRoute = 'Search2Record';
                } else {
                    $recordRoute = 'Record';
                }

                echo '<div class="additional_copies"><a href="/vufind/'.$recordRoute.'/'.$id.'">'.$this->transEsc('additional_copies').'...</a></div>';
            }
            if(!$list) echo '</div>';
        }
        if($mode == 'break_on_first') break;
    }
}

?>
